/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UI;




import java.sql.ResultSet;
import java.time.LocalDate;
import java.util.Arrays;
import java.util.List;
import javax.swing.*;




public class VentanaInicio extends javax.swing.JFrame{
   
    private NavegacionController nav = new NavegacionController();
    
    LocalDate hoy = LocalDate.now();
    
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VentanaInicio.class.getName());

    /**
     * Creates new form VentanaInicio
     */
    public VentanaInicio() {
        initComponents();
        setVisible(true);
        setLocationRelativeTo(null);
        internalHome.setVisible(true);
        internalVehiculos.setVisible(false);
        internalModelos.setVisible(false);
        internalVentas.setVisible(false);
        internalProximamente.setVisible(false);

       
        
        pack();
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        groupBusquedaVehiculos = new javax.swing.ButtonGroup();
        groupBusquedaModelos = new javax.swing.ButtonGroup();
        groupBusquedaVentas = new javax.swing.ButtonGroup();
        bg = new javax.swing.JPanel();
        sidePane = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        btnCerrarSesion = new javax.swing.JButton();
        btnHome = new javax.swing.JButton();
        btnVehiculos = new javax.swing.JButton();
        btnModelos = new javax.swing.JButton();
        btnVentas = new javax.swing.JButton();
        btnEmpleados = new javax.swing.JButton();
        btnClientes = new javax.swing.JButton();
        btnDocumentacion = new javax.swing.JButton();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        internalHome = new javax.swing.JInternalFrame();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel81 = new javax.swing.JLabel();
        jPanel21 = new javax.swing.JPanel();
        jLabel82 = new javax.swing.JLabel();
        btnHomeGrafica = new javax.swing.JButton();
        btnHomeVista = new javax.swing.JButton();
        btnHomeReporte = new javax.swing.JButton();
        btnHomeHistorialPrecios = new javax.swing.JButton();
        btnHomeVehiculosEliminados = new javax.swing.JButton();
        internalVehiculos = new javax.swing.JInternalFrame();
        jPanel2 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btnModificarVehiculos = new javax.swing.JButton();
        btnAgregarVehiculos = new javax.swing.JButton();
        btnEliminarVehiculos = new javax.swing.JButton();
        cajaNumVehiculoBuscar = new javax.swing.JTextField();
        radioTipoBusqueda = new javax.swing.JRadioButton();
        radioModeloBusqueda = new javax.swing.JRadioButton();
        cajaNumSerieBuscar = new javax.swing.JTextField();
        comboModeloBusqueda = new javax.swing.JComboBox<>();
        radioNumSerieBusqueda = new javax.swing.JRadioButton();
        comboEstadoBusqueda = new javax.swing.JComboBox<>();
        radioNumVehiculoBusqueda = new javax.swing.JRadioButton();
        comboTipoBusqueda = new javax.swing.JComboBox<>();
        radioTodosBusqueda = new javax.swing.JRadioButton();
        radioPrecioBusqueda1 = new javax.swing.JRadioButton();
        comboPrecioBusqueda1 = new javax.swing.JComboBox<>();
        radioAnioBusqueda1 = new javax.swing.JRadioButton();
        comboAnioBusqueda1 = new javax.swing.JComboBox<>();
        radioEstadoBusqueda1 = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaVehiculos = new javax.swing.JTable();
        internalModelos = new javax.swing.JInternalFrame();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaModelos = new javax.swing.JTable();
        jPanel11 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        btnEliminarModelos = new javax.swing.JButton();
        btnAgregarModelos = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        btnActualizarModelos = new javax.swing.JButton();
        jLabel23 = new javax.swing.JLabel();
        radioNumeroCilindros = new javax.swing.JRadioButton();
        radioidModeloBusqueda = new javax.swing.JRadioButton();
        cajaNombreModeloBusqueda = new javax.swing.JTextField();
        radioNombreModelo = new javax.swing.JRadioButton();
        comboAnioModeloBuscar = new javax.swing.JComboBox<>();
        radioAnioModeloBuscar = new javax.swing.JRadioButton();
        radioFabricanteModelo = new javax.swing.JRadioButton();
        comboNumeroCilindrosBuscar = new javax.swing.JComboBox<>();
        radioPais = new javax.swing.JRadioButton();
        radioNumeroPuertas = new javax.swing.JRadioButton();
        radioPeso = new javax.swing.JRadioButton();
        radioPasajeros = new javax.swing.JRadioButton();
        radioTodosModelos = new javax.swing.JRadioButton();
        cajaFabricanteModeloBusqueda = new javax.swing.JTextField();
        cajaPaisModeloBusqueda = new javax.swing.JTextField();
        cajaIDModeloBusqueda = new javax.swing.JTextField();
        cajaModeloPesoBusqueda = new javax.swing.JTextField();
        cajaModeloPasajerosBusqueda = new javax.swing.JTextField();
        cajaModeloPuertasBusqueda = new javax.swing.JTextField();
        internalVentas = new javax.swing.JInternalFrame();
        jPanel4 = new javax.swing.JPanel();
        jPanel16 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        btnEliminarVentas = new javax.swing.JButton();
        btnAgregarVentas = new javax.swing.JButton();
        btnActualizarVentas = new javax.swing.JButton();
        jLabel62 = new javax.swing.JLabel();
        radioIDVentaVentas = new javax.swing.JRadioButton();
        radioTodosVentas = new javax.swing.JRadioButton();
        cajaIDVentasBuscar = new javax.swing.JTextField();
        comboVentasVehiculosBuscar = new javax.swing.JComboBox<>();
        radioMesVentas = new javax.swing.JRadioButton();
        comboVentasMesBuscar = new javax.swing.JComboBox<>();
        radioPrecioVentas = new javax.swing.JRadioButton();
        comboVentasPrecioBuscar = new javax.swing.JComboBox<>();
        radioIdClienteVentas = new javax.swing.JRadioButton();
        comboVentasClienteBuscar = new javax.swing.JComboBox<>();
        radioIDEmpleadoVentas = new javax.swing.JRadioButton();
        comboVentasEmpleadoBuscar = new javax.swing.JComboBox<>();
        radioIDVehiculoVentas = new javax.swing.JRadioButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tablaVentas = new javax.swing.JTable();
        radioVentasPagoBuscar = new javax.swing.JRadioButton();
        comboVentasPagoBuscar = new javax.swing.JComboBox<>();
        internalProximamente = new javax.swing.JInternalFrame();
        jPanel5 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        internalVehiculosEliminados = new javax.swing.JInternalFrame();
        jPanel22 = new javax.swing.JPanel();
        jPanel23 = new javax.swing.JPanel();
        jLabel83 = new javax.swing.JLabel();
        jLabel84 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tablaVehiculosEliminados = new javax.swing.JTable();
        btnVehiculosEliminadosCerrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Autos Amistosos");
        setResizable(false);

        bg.setBackground(new java.awt.Color(255, 255, 255));
        bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        sidePane.setBackground(new java.awt.Color(247, 227, 178));
        sidePane.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel13.setIcon(new javax.swing.ImageIcon("C:\\Users\\eduar\\Documents\\ITSJ\\5. Quinto Semestre\\Taller de bases de datos\\Proyecto final\\Proyecto_Final_TBD_Escritorio\\src\\main\\java\\img\\LOGO_chico.png")); // NOI18N
        sidePane.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, 140, 140));

        btnCerrarSesion.setBackground(new java.awt.Color(227, 211, 163));
        btnCerrarSesion.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnCerrarSesion.setForeground(new java.awt.Color(0, 0, 0));
        btnCerrarSesion.setIcon(new javax.swing.ImageIcon("C:\\Users\\eduar\\Documents\\ITSJ\\5. Quinto Semestre\\Taller de bases de datos\\Proyecto final\\Proyecto_Final_TBD_Escritorio\\src\\main\\java\\img\\cerrar_sesion.png")); // NOI18N
        btnCerrarSesion.setText("Cerrar Sesión");
        btnCerrarSesion.setToolTipText("");
        btnCerrarSesion.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnCerrarSesion.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnCerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarSesionActionPerformed(evt);
            }
        });
        sidePane.add(btnCerrarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 420, 220, 40));

        btnHome.setBackground(new java.awt.Color(214, 198, 152));
        btnHome.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnHome.setForeground(new java.awt.Color(0, 0, 0));
        btnHome.setIcon(new javax.swing.ImageIcon("C:\\Users\\eduar\\Documents\\ITSJ\\6. Sexto Semestre\\Administración de Bases de Datos\\Proyecto Final\\Proyecto_Final_ABD_AutosAmistosos\\src\\main\\java\\img\\home.png")); // NOI18N
        btnHome.setText("Home");
        btnHome.setToolTipText("");
        btnHome.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnHome.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHomeActionPerformed(evt);
            }
        });
        sidePane.add(btnHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 220, 40));

        btnVehiculos.setBackground(new java.awt.Color(227, 211, 163));
        btnVehiculos.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnVehiculos.setForeground(new java.awt.Color(0, 0, 0));
        btnVehiculos.setIcon(new javax.swing.ImageIcon("C:\\Users\\eduar\\Documents\\ITSJ\\5. Quinto Semestre\\Taller de bases de datos\\Proyecto final\\Proyecto_Final_TBD_Escritorio\\src\\main\\java\\img\\carro.png")); // NOI18N
        btnVehiculos.setText("Vehículos");
        btnVehiculos.setToolTipText("");
        btnVehiculos.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnVehiculos.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnVehiculos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVehiculosActionPerformed(evt);
            }
        });
        sidePane.add(btnVehiculos, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 220, 40));

        btnModelos.setBackground(new java.awt.Color(227, 211, 163));
        btnModelos.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnModelos.setForeground(new java.awt.Color(0, 0, 0));
        btnModelos.setIcon(new javax.swing.ImageIcon("C:\\Users\\eduar\\Documents\\ITSJ\\5. Quinto Semestre\\Taller de bases de datos\\Proyecto final\\Proyecto_Final_TBD_Escritorio\\src\\main\\java\\img\\modelo.png")); // NOI18N
        btnModelos.setText("Modelos");
        btnModelos.setToolTipText("");
        btnModelos.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnModelos.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnModelos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModelosActionPerformed(evt);
            }
        });
        sidePane.add(btnModelos, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 220, 220, 40));

        btnVentas.setBackground(new java.awt.Color(227, 211, 163));
        btnVentas.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnVentas.setForeground(new java.awt.Color(0, 0, 0));
        btnVentas.setIcon(new javax.swing.ImageIcon("C:\\Users\\eduar\\Documents\\ITSJ\\5. Quinto Semestre\\Taller de bases de datos\\Proyecto final\\Proyecto_Final_TBD_Escritorio\\src\\main\\java\\img\\ventas.png")); // NOI18N
        btnVentas.setText("Ventas");
        btnVentas.setToolTipText("");
        btnVentas.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnVentas.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnVentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVentasActionPerformed(evt);
            }
        });
        sidePane.add(btnVentas, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, 220, 40));

        btnEmpleados.setBackground(new java.awt.Color(227, 211, 163));
        btnEmpleados.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnEmpleados.setForeground(new java.awt.Color(0, 0, 0));
        btnEmpleados.setIcon(new javax.swing.ImageIcon("C:\\Users\\eduar\\Documents\\ITSJ\\5. Quinto Semestre\\Taller de bases de datos\\Proyecto final\\Proyecto_Final_TBD_Escritorio\\src\\main\\java\\img\\empleados.png")); // NOI18N
        btnEmpleados.setText("Empleados");
        btnEmpleados.setToolTipText("");
        btnEmpleados.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnEmpleados.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnEmpleados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEmpleadosActionPerformed(evt);
            }
        });
        sidePane.add(btnEmpleados, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 300, 220, 40));

        btnClientes.setBackground(new java.awt.Color(227, 211, 163));
        btnClientes.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnClientes.setForeground(new java.awt.Color(0, 0, 0));
        btnClientes.setIcon(new javax.swing.ImageIcon("C:\\Users\\eduar\\Documents\\ITSJ\\5. Quinto Semestre\\Taller de bases de datos\\Proyecto final\\Proyecto_Final_TBD_Escritorio\\src\\main\\java\\img\\cliente.png")); // NOI18N
        btnClientes.setText("Clientes");
        btnClientes.setToolTipText("");
        btnClientes.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnClientes.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClientesActionPerformed(evt);
            }
        });
        sidePane.add(btnClientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 340, 220, 40));

        btnDocumentacion.setBackground(new java.awt.Color(227, 211, 163));
        btnDocumentacion.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnDocumentacion.setForeground(new java.awt.Color(0, 0, 0));
        btnDocumentacion.setIcon(new javax.swing.ImageIcon("C:\\Users\\eduar\\Documents\\ITSJ\\5. Quinto Semestre\\Taller de bases de datos\\Proyecto final\\Proyecto_Final_TBD_Escritorio\\src\\main\\java\\img\\documento.png")); // NOI18N
        btnDocumentacion.setText("Documentación");
        btnDocumentacion.setToolTipText("");
        btnDocumentacion.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnDocumentacion.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnDocumentacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDocumentacionActionPerformed(evt);
            }
        });
        sidePane.add(btnDocumentacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 380, 220, 40));

        bg.add(sidePane, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 221, 615));

        internalHome.setBackground(new java.awt.Color(255, 255, 255));
        internalHome.setTitle("Home");
        internalHome.setToolTipText("");
        internalHome.setVisible(false);
        internalHome.getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(247, 227, 178));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Hola Bienvenido a Autos Amistosos");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(190, 0, 370, 66);

        jLabel81.setIcon(new javax.swing.ImageIcon("C:\\Users\\eduar\\Documents\\ITSJ\\5. Quinto Semestre\\Taller de bases de datos\\Proyecto final\\Proyecto_Final_TBD_Escritorio\\src\\main\\java\\img\\LOGO.png")); // NOI18N
        jPanel1.add(jLabel81);
        jLabel81.setBounds(270, 50, 200, 190);

        jPanel21.setBackground(new java.awt.Color(255, 255, 255));
        jPanel21.setLayout(null);

        jLabel82.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel82.setForeground(new java.awt.Color(0, 0, 0));
        jLabel82.setText("Acciones Rápidas");
        jPanel21.add(jLabel82);
        jLabel82.setBounds(10, 10, 150, 30);

        btnHomeGrafica.setBackground(new java.awt.Color(227, 211, 163));
        btnHomeGrafica.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnHomeGrafica.setForeground(new java.awt.Color(0, 0, 0));
        btnHomeGrafica.setIcon(new javax.swing.ImageIcon("C:\\Users\\eduar\\Documents\\ITSJ\\5. Quinto Semestre\\Taller de bases de datos\\Proyecto final\\Proyecto_Final_TBD_Escritorio\\src\\main\\java\\img\\grafica.png")); // NOI18N
        btnHomeGrafica.setText("Gráfica Ventas");
        jPanel21.add(btnHomeGrafica);
        btnHomeGrafica.setBounds(540, 70, 200, 60);

        btnHomeVista.setBackground(new java.awt.Color(227, 211, 163));
        btnHomeVista.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnHomeVista.setForeground(new java.awt.Color(0, 0, 0));
        btnHomeVista.setIcon(new javax.swing.ImageIcon("C:\\Users\\eduar\\Documents\\ITSJ\\5. Quinto Semestre\\Taller de bases de datos\\Proyecto final\\Proyecto_Final_TBD_Escritorio\\src\\main\\java\\img\\vista.png")); // NOI18N
        btnHomeVista.setText("Vista Vehículos-Modelo");
        btnHomeVista.setToolTipText("");
        jPanel21.add(btnHomeVista);
        btnHomeVista.setBounds(10, 70, 240, 60);

        btnHomeReporte.setBackground(new java.awt.Color(227, 211, 163));
        btnHomeReporte.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnHomeReporte.setForeground(new java.awt.Color(0, 0, 0));
        btnHomeReporte.setIcon(new javax.swing.ImageIcon("C:\\Users\\eduar\\Documents\\ITSJ\\5. Quinto Semestre\\Taller de bases de datos\\Proyecto final\\Proyecto_Final_TBD_Escritorio\\src\\main\\java\\img\\reporte.png")); // NOI18N
        btnHomeReporte.setText("Reporte Ventas");
        jPanel21.add(btnHomeReporte);
        btnHomeReporte.setBounds(290, 70, 210, 60);

        btnHomeHistorialPrecios.setBackground(new java.awt.Color(227, 211, 163));
        btnHomeHistorialPrecios.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnHomeHistorialPrecios.setForeground(new java.awt.Color(0, 0, 0));
        btnHomeHistorialPrecios.setIcon(new javax.swing.ImageIcon("C:\\Users\\eduar\\Documents\\ITSJ\\5. Quinto Semestre\\Taller de bases de datos\\Proyecto final\\Proyecto_Final_TBD_Escritorio\\src\\main\\java\\img\\ventas.png")); // NOI18N
        btnHomeHistorialPrecios.setText("Historial Precios");
        btnHomeHistorialPrecios.setToolTipText("");
        jPanel21.add(btnHomeHistorialPrecios);
        btnHomeHistorialPrecios.setBounds(450, 180, 240, 60);

        btnHomeVehiculosEliminados.setBackground(new java.awt.Color(227, 211, 163));
        btnHomeVehiculosEliminados.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnHomeVehiculosEliminados.setForeground(new java.awt.Color(0, 0, 0));
        btnHomeVehiculosEliminados.setIcon(new javax.swing.ImageIcon("C:\\Users\\eduar\\Documents\\ITSJ\\5. Quinto Semestre\\Taller de bases de datos\\Proyecto final\\Proyecto_Final_TBD_Escritorio\\src\\main\\java\\img\\carro.png")); // NOI18N
        btnHomeVehiculosEliminados.setText("Vehículos Eliminados");
        btnHomeVehiculosEliminados.setToolTipText("");
        jPanel21.add(btnHomeVehiculosEliminados);
        btnHomeVehiculosEliminados.setBounds(90, 180, 240, 60);

        jPanel1.add(jPanel21);
        jPanel21.setBounds(0, 240, 760, 330);

        internalHome.getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 760, 570);

        jDesktopPane1.add(internalHome);
        internalHome.setBounds(0, 0, 770, 610);

        internalVehiculos.setTitle("Vehiculos");
        internalVehiculos.setVisible(false);
        internalVehiculos.getContentPane().setLayout(null);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(null);

        jPanel6.setBackground(new java.awt.Color(214, 198, 152));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Vehículos");

        jLabel6.setIcon(new javax.swing.ImageIcon("C:\\Users\\eduar\\Documents\\ITSJ\\5. Quinto Semestre\\Taller de bases de datos\\Proyecto final\\Proyecto_Final_TBD_Escritorio\\src\\main\\java\\img\\logo_oscuro.png")); // NOI18N

        btnModificarVehiculos.setBackground(new java.awt.Color(227, 211, 163));
        btnModificarVehiculos.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnModificarVehiculos.setForeground(new java.awt.Color(0, 0, 0));
        btnModificarVehiculos.setIcon(new javax.swing.ImageIcon("C:\\Users\\eduar\\Documents\\ITSJ\\5. Quinto Semestre\\Taller de bases de datos\\Proyecto final\\Proyecto_Final_TBD_Escritorio\\src\\main\\java\\img\\actualizar.png")); // NOI18N
        btnModificarVehiculos.setText("Actualizar");
        btnModificarVehiculos.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        btnModificarVehiculos.setEnabled(false);

        btnAgregarVehiculos.setBackground(new java.awt.Color(227, 211, 163));
        btnAgregarVehiculos.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnAgregarVehiculos.setForeground(new java.awt.Color(0, 0, 0));
        btnAgregarVehiculos.setIcon(new javax.swing.ImageIcon("C:\\Users\\eduar\\Documents\\ITSJ\\5. Quinto Semestre\\Taller de bases de datos\\Proyecto final\\Proyecto_Final_TBD_Escritorio\\src\\main\\java\\img\\agregar.png")); // NOI18N
        btnAgregarVehiculos.setText("Agregar");
        btnAgregarVehiculos.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        btnEliminarVehiculos.setBackground(new java.awt.Color(227, 211, 163));
        btnEliminarVehiculos.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnEliminarVehiculos.setForeground(new java.awt.Color(0, 0, 0));
        btnEliminarVehiculos.setIcon(new javax.swing.ImageIcon("C:\\Users\\eduar\\Documents\\ITSJ\\5. Quinto Semestre\\Taller de bases de datos\\Proyecto final\\Proyecto_Final_TBD_Escritorio\\src\\main\\java\\img\\eliminar.png")); // NOI18N
        btnEliminarVehiculos.setText("Eliminar");
        btnEliminarVehiculos.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        btnEliminarVehiculos.setEnabled(false);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 204, Short.MAX_VALUE)
                .addComponent(btnAgregarVehiculos, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnModificarVehiculos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnEliminarVehiculos)
                .addGap(43, 43, 43)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnAgregarVehiculos, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnEliminarVehiculos, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnModificarVehiculos, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.add(jPanel6);
        jPanel6.setBounds(0, 0, 760, 60);

        cajaNumVehiculoBuscar.setBackground(new java.awt.Color(255, 255, 255));
        cajaNumVehiculoBuscar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jPanel2.add(cajaNumVehiculoBuscar);
        cajaNumVehiculoBuscar.setBounds(30, 100, 210, 30);

        groupBusquedaVehiculos.add(radioTipoBusqueda);
        radioTipoBusqueda.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        radioTipoBusqueda.setForeground(new java.awt.Color(0, 0, 0));
        radioTipoBusqueda.setText("Tipo");
        jPanel2.add(radioTipoBusqueda);
        radioTipoBusqueda.setBounds(510, 150, 200, 25);

        groupBusquedaVehiculos.add(radioModeloBusqueda);
        radioModeloBusqueda.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        radioModeloBusqueda.setForeground(new java.awt.Color(0, 0, 0));
        radioModeloBusqueda.setText("Modelo");
        jPanel2.add(radioModeloBusqueda);
        radioModeloBusqueda.setBounds(510, 70, 170, 25);

        cajaNumSerieBuscar.setBackground(new java.awt.Color(255, 255, 255));
        cajaNumSerieBuscar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jPanel2.add(cajaNumSerieBuscar);
        cajaNumSerieBuscar.setBounds(270, 100, 210, 30);

        comboModeloBusqueda.setBackground(new java.awt.Color(214, 198, 152));
        comboModeloBusqueda.setForeground(new java.awt.Color(0, 0, 0));
        jPanel2.add(comboModeloBusqueda);
        comboModeloBusqueda.setBounds(510, 100, 210, 26);

        groupBusquedaVehiculos.add(radioNumSerieBusqueda);
        radioNumSerieBusqueda.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        radioNumSerieBusqueda.setForeground(new java.awt.Color(0, 0, 0));
        radioNumSerieBusqueda.setText("Número de Serie");
        jPanel2.add(radioNumSerieBusqueda);
        radioNumSerieBusqueda.setBounds(260, 70, 170, 25);

        comboEstadoBusqueda.setBackground(new java.awt.Color(214, 198, 152));
        comboEstadoBusqueda.setForeground(new java.awt.Color(0, 0, 0));
        jPanel2.add(comboEstadoBusqueda);
        comboEstadoBusqueda.setBounds(30, 250, 210, 26);

        groupBusquedaVehiculos.add(radioNumVehiculoBusqueda);
        radioNumVehiculoBusqueda.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        radioNumVehiculoBusqueda.setForeground(new java.awt.Color(0, 0, 0));
        radioNumVehiculoBusqueda.setText("Número de Vehículo");
        jPanel2.add(radioNumVehiculoBusqueda);
        radioNumVehiculoBusqueda.setBounds(30, 70, 170, 25);

        comboTipoBusqueda.setBackground(new java.awt.Color(214, 198, 152));
        comboTipoBusqueda.setForeground(new java.awt.Color(0, 0, 0));
        jPanel2.add(comboTipoBusqueda);
        comboTipoBusqueda.setBounds(510, 180, 210, 26);

        groupBusquedaVehiculos.add(radioTodosBusqueda);
        radioTodosBusqueda.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        radioTodosBusqueda.setForeground(new java.awt.Color(0, 0, 0));
        radioTodosBusqueda.setSelected(true);
        radioTodosBusqueda.setText("Mostrar Todos los Vehículos");
        jPanel2.add(radioTodosBusqueda);
        radioTodosBusqueda.setBounds(290, 240, 230, 25);

        groupBusquedaVehiculos.add(radioPrecioBusqueda1);
        radioPrecioBusqueda1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        radioPrecioBusqueda1.setForeground(new java.awt.Color(0, 0, 0));
        radioPrecioBusqueda1.setText("Precio Menor A:");
        jPanel2.add(radioPrecioBusqueda1);
        radioPrecioBusqueda1.setBounds(270, 150, 200, 25);

        comboPrecioBusqueda1.setBackground(new java.awt.Color(214, 198, 152));
        comboPrecioBusqueda1.setForeground(new java.awt.Color(0, 0, 0));
        jPanel2.add(comboPrecioBusqueda1);
        comboPrecioBusqueda1.setBounds(270, 180, 210, 26);

        groupBusquedaVehiculos.add(radioAnioBusqueda1);
        radioAnioBusqueda1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        radioAnioBusqueda1.setForeground(new java.awt.Color(0, 0, 0));
        radioAnioBusqueda1.setText("Año de Fabricación");
        jPanel2.add(radioAnioBusqueda1);
        radioAnioBusqueda1.setBounds(30, 150, 200, 25);

        comboAnioBusqueda1.setBackground(new java.awt.Color(214, 198, 152));
        comboAnioBusqueda1.setForeground(new java.awt.Color(0, 0, 0));
        jPanel2.add(comboAnioBusqueda1);
        comboAnioBusqueda1.setBounds(30, 180, 210, 26);

        groupBusquedaVehiculos.add(radioEstadoBusqueda1);
        radioEstadoBusqueda1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        radioEstadoBusqueda1.setForeground(new java.awt.Color(0, 0, 0));
        radioEstadoBusqueda1.setText("Estado");
        jPanel2.add(radioEstadoBusqueda1);
        radioEstadoBusqueda1.setBounds(30, 220, 200, 25);

        tablaVehiculos.setBackground(new java.awt.Color(247, 227, 178));
        tablaVehiculos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID_Vehiculo", "Numero_Serie", "ID_Modelo", "Fecha_Fabricacion", "Precio", "Kilometraje", "Fecha_Entrada", "Tipo", "Estado"
            }
        ));
        tablaVehiculos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tablaVehiculosMouseReleased(evt);
            }
        });
        jScrollPane1.setViewportView(tablaVehiculos);

        jPanel2.add(jScrollPane1);
        jScrollPane1.setBounds(20, 290, 720, 270);

        internalVehiculos.getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 0, 760, 580);

        jDesktopPane1.add(internalVehiculos);
        internalVehiculos.setBounds(0, 0, 770, 610);

        internalModelos.setTitle("Modelos");
        internalModelos.setVisible(false);
        internalModelos.getContentPane().setLayout(null);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(null);

        tablaModelos.setBackground(new java.awt.Color(214, 198, 152));
        tablaModelos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tablaModelos);

        jPanel3.add(jScrollPane2);
        jScrollPane2.setBounds(20, 260, 720, 280);

        jPanel11.setBackground(new java.awt.Color(214, 198, 152));
        jPanel11.setLayout(null);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Modelos");
        jPanel11.add(jLabel3);
        jLabel3.setBounds(70, 130, 420, 90);

        btnEliminarModelos.setBackground(new java.awt.Color(227, 211, 163));
        btnEliminarModelos.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnEliminarModelos.setForeground(new java.awt.Color(0, 0, 0));
        btnEliminarModelos.setIcon(new javax.swing.ImageIcon("C:\\Users\\eduar\\Documents\\ITSJ\\5. Quinto Semestre\\Taller de bases de datos\\Proyecto final\\Proyecto_Final_TBD_Escritorio\\src\\main\\java\\img\\eliminar.png")); // NOI18N
        btnEliminarModelos.setText("Eliminar");
        btnEliminarModelos.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        btnEliminarModelos.setEnabled(false);
        jPanel11.add(btnEliminarModelos);
        btnEliminarModelos.setBounds(520, 10, 120, 40);

        btnAgregarModelos.setBackground(new java.awt.Color(227, 211, 163));
        btnAgregarModelos.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnAgregarModelos.setForeground(new java.awt.Color(0, 0, 0));
        btnAgregarModelos.setIcon(new javax.swing.ImageIcon("C:\\Users\\eduar\\Documents\\ITSJ\\5. Quinto Semestre\\Taller de bases de datos\\Proyecto final\\Proyecto_Final_TBD_Escritorio\\src\\main\\java\\img\\agregar.png")); // NOI18N
        btnAgregarModelos.setText("Agregar");
        btnAgregarModelos.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jPanel11.add(btnAgregarModelos);
        btnAgregarModelos.setBounds(230, 10, 120, 40);

        jLabel20.setIcon(new javax.swing.ImageIcon("C:\\Users\\eduar\\Documents\\ITSJ\\5. Quinto Semestre\\Taller de bases de datos\\Proyecto final\\Proyecto_Final_TBD_Escritorio\\src\\main\\java\\img\\logo_oscuro.png")); // NOI18N
        jPanel11.add(jLabel20);
        jLabel20.setBounds(690, 0, 50, 58);

        btnActualizarModelos.setBackground(new java.awt.Color(227, 211, 163));
        btnActualizarModelos.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnActualizarModelos.setForeground(new java.awt.Color(0, 0, 0));
        btnActualizarModelos.setIcon(new javax.swing.ImageIcon("C:\\Users\\eduar\\Documents\\ITSJ\\5. Quinto Semestre\\Taller de bases de datos\\Proyecto final\\Proyecto_Final_TBD_Escritorio\\src\\main\\java\\img\\actualizar.png")); // NOI18N
        btnActualizarModelos.setText("Actualizar");
        btnActualizarModelos.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        btnActualizarModelos.setEnabled(false);
        jPanel11.add(btnActualizarModelos);
        btnActualizarModelos.setBounds(370, 10, 130, 40);

        jLabel23.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(0, 0, 0));
        jLabel23.setText("Modelos");
        jPanel11.add(jLabel23);
        jLabel23.setBounds(10, 0, 140, 50);

        jPanel3.add(jPanel11);
        jPanel11.setBounds(0, 0, 760, 60);

        groupBusquedaModelos.add(radioNumeroCilindros);
        radioNumeroCilindros.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        radioNumeroCilindros.setForeground(new java.awt.Color(0, 0, 0));
        radioNumeroCilindros.setText("Número Cilindros");
        jPanel3.add(radioNumeroCilindros);
        radioNumeroCilindros.setBounds(590, 70, 130, 20);

        groupBusquedaModelos.add(radioidModeloBusqueda);
        radioidModeloBusqueda.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        radioidModeloBusqueda.setForeground(new java.awt.Color(0, 0, 0));
        radioidModeloBusqueda.setText("ID Modelo");
        jPanel3.add(radioidModeloBusqueda);
        radioidModeloBusqueda.setBounds(30, 70, 83, 21);

        cajaNombreModeloBusqueda.setBackground(new java.awt.Color(255, 255, 255));
        cajaNombreModeloBusqueda.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        cajaNombreModeloBusqueda.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                cajaNombreModeloBusquedaKeyReleased(evt);
            }
        });
        jPanel3.add(cajaNombreModeloBusqueda);
        cajaNombreModeloBusqueda.setBounds(160, 100, 120, 18);

        groupBusquedaModelos.add(radioNombreModelo);
        radioNombreModelo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        radioNombreModelo.setForeground(new java.awt.Color(0, 0, 0));
        radioNombreModelo.setText("Nombre Modelo");
        jPanel3.add(radioNombreModelo);
        radioNombreModelo.setBounds(160, 70, 130, 21);

        comboAnioModeloBuscar.setBackground(new java.awt.Color(214, 198, 152));
        comboAnioModeloBuscar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        comboAnioModeloBuscar.setForeground(new java.awt.Color(0, 0, 0));
        jPanel3.add(comboAnioModeloBuscar);
        comboAnioModeloBuscar.setBounds(310, 100, 90, 26);

        groupBusquedaModelos.add(radioAnioModeloBuscar);
        radioAnioModeloBuscar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        radioAnioModeloBuscar.setForeground(new java.awt.Color(0, 0, 0));
        radioAnioModeloBuscar.setText("Año Modelo");
        radioAnioModeloBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rformed(evt);
            }
        });
        jPanel3.add(radioAnioModeloBuscar);
        radioAnioModeloBuscar.setBounds(310, 70, 100, 21);

        groupBusquedaModelos.add(radioFabricanteModelo);
        radioFabricanteModelo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        radioFabricanteModelo.setForeground(new java.awt.Color(0, 0, 0));
        radioFabricanteModelo.setText("Fabricante");
        jPanel3.add(radioFabricanteModelo);
        radioFabricanteModelo.setBounds(440, 70, 100, 21);

        comboNumeroCilindrosBuscar.setBackground(new java.awt.Color(214, 198, 152));
        comboNumeroCilindrosBuscar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        comboNumeroCilindrosBuscar.setForeground(new java.awt.Color(0, 0, 0));
        jPanel3.add(comboNumeroCilindrosBuscar);
        comboNumeroCilindrosBuscar.setBounds(590, 100, 130, 26);

        groupBusquedaModelos.add(radioPais);
        radioPais.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        radioPais.setForeground(new java.awt.Color(0, 0, 0));
        radioPais.setText("País Fabricación");
        jPanel3.add(radioPais);
        radioPais.setBounds(450, 150, 111, 20);

        groupBusquedaModelos.add(radioNumeroPuertas);
        radioNumeroPuertas.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        radioNumeroPuertas.setForeground(new java.awt.Color(0, 0, 0));
        radioNumeroPuertas.setText("Número Puertas");
        jPanel3.add(radioNumeroPuertas);
        radioNumeroPuertas.setBounds(20, 150, 130, 20);

        groupBusquedaModelos.add(radioPeso);
        radioPeso.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        radioPeso.setForeground(new java.awt.Color(0, 0, 0));
        radioPeso.setText("Peso (KG)");
        jPanel3.add(radioPeso);
        radioPeso.setBounds(170, 150, 130, 20);

        groupBusquedaModelos.add(radioPasajeros);
        radioPasajeros.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        radioPasajeros.setForeground(new java.awt.Color(0, 0, 0));
        radioPasajeros.setText("Capacidad Pasajeros");
        jPanel3.add(radioPasajeros);
        radioPasajeros.setBounds(300, 150, 140, 20);

        groupBusquedaModelos.add(radioTodosModelos);
        radioTodosModelos.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        radioTodosModelos.setForeground(new java.awt.Color(0, 0, 0));
        radioTodosModelos.setSelected(true);
        radioTodosModelos.setText("Mostrar todos los Modelos");
        jPanel3.add(radioTodosModelos);
        radioTodosModelos.setBounds(570, 150, 180, 20);

        cajaFabricanteModeloBusqueda.setBackground(new java.awt.Color(255, 255, 255));
        cajaFabricanteModeloBusqueda.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jPanel3.add(cajaFabricanteModeloBusqueda);
        cajaFabricanteModeloBusqueda.setBounds(440, 100, 120, 18);

        cajaPaisModeloBusqueda.setBackground(new java.awt.Color(255, 255, 255));
        cajaPaisModeloBusqueda.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jPanel3.add(cajaPaisModeloBusqueda);
        cajaPaisModeloBusqueda.setBounds(450, 180, 120, 18);

        cajaIDModeloBusqueda.setBackground(new java.awt.Color(255, 255, 255));
        cajaIDModeloBusqueda.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jPanel3.add(cajaIDModeloBusqueda);
        cajaIDModeloBusqueda.setBounds(30, 100, 120, 18);

        cajaModeloPesoBusqueda.setBackground(new java.awt.Color(255, 255, 255));
        cajaModeloPesoBusqueda.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jPanel3.add(cajaModeloPesoBusqueda);
        cajaModeloPesoBusqueda.setBounds(160, 180, 120, 18);

        cajaModeloPasajerosBusqueda.setBackground(new java.awt.Color(255, 255, 255));
        cajaModeloPasajerosBusqueda.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jPanel3.add(cajaModeloPasajerosBusqueda);
        cajaModeloPasajerosBusqueda.setBounds(310, 180, 120, 18);

        cajaModeloPuertasBusqueda.setBackground(new java.awt.Color(255, 255, 255));
        cajaModeloPuertasBusqueda.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jPanel3.add(cajaModeloPuertasBusqueda);
        cajaModeloPuertasBusqueda.setBounds(20, 180, 120, 18);

        internalModelos.getContentPane().add(jPanel3);
        jPanel3.setBounds(0, 0, 760, 580);

        jDesktopPane1.add(internalModelos);
        internalModelos.setBounds(0, 0, 770, 610);

        internalVentas.setTitle("Ventas");
        internalVentas.setVisible(true);
        internalVentas.getContentPane().setLayout(null);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(null);

        jPanel16.setBackground(new java.awt.Color(214, 198, 152));
        jPanel16.setLayout(null);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Ventas");
        jPanel16.add(jLabel4);
        jLabel4.setBounds(10, 10, 90, 40);

        btnEliminarVentas.setBackground(new java.awt.Color(227, 211, 163));
        btnEliminarVentas.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnEliminarVentas.setForeground(new java.awt.Color(0, 0, 0));
        btnEliminarVentas.setIcon(new javax.swing.ImageIcon("C:\\Users\\eduar\\Documents\\ITSJ\\5. Quinto Semestre\\Taller de bases de datos\\Proyecto final\\Proyecto_Final_TBD_Escritorio\\src\\main\\java\\img\\eliminar.png")); // NOI18N
        btnEliminarVentas.setText("Eliminar");
        btnEliminarVentas.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        btnEliminarVentas.setEnabled(false);
        jPanel16.add(btnEliminarVentas);
        btnEliminarVentas.setBounds(560, 10, 120, 40);

        btnAgregarVentas.setBackground(new java.awt.Color(227, 211, 163));
        btnAgregarVentas.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnAgregarVentas.setForeground(new java.awt.Color(0, 0, 0));
        btnAgregarVentas.setIcon(new javax.swing.ImageIcon("C:\\Users\\eduar\\Documents\\ITSJ\\5. Quinto Semestre\\Taller de bases de datos\\Proyecto final\\Proyecto_Final_TBD_Escritorio\\src\\main\\java\\img\\agregar.png")); // NOI18N
        btnAgregarVentas.setText("Agregar");
        btnAgregarVentas.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jPanel16.add(btnAgregarVentas);
        btnAgregarVentas.setBounds(290, 10, 120, 40);

        btnActualizarVentas.setBackground(new java.awt.Color(227, 211, 163));
        btnActualizarVentas.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnActualizarVentas.setForeground(new java.awt.Color(0, 0, 0));
        btnActualizarVentas.setIcon(new javax.swing.ImageIcon("C:\\Users\\eduar\\Documents\\ITSJ\\5. Quinto Semestre\\Taller de bases de datos\\Proyecto final\\Proyecto_Final_TBD_Escritorio\\src\\main\\java\\img\\actualizar.png")); // NOI18N
        btnActualizarVentas.setText("Actualizar");
        btnActualizarVentas.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        btnActualizarVentas.setEnabled(false);
        jPanel16.add(btnActualizarVentas);
        btnActualizarVentas.setBounds(420, 10, 130, 40);

        jLabel62.setIcon(new javax.swing.ImageIcon("C:\\Users\\eduar\\Documents\\ITSJ\\5. Quinto Semestre\\Taller de bases de datos\\Proyecto final\\Proyecto_Final_TBD_Escritorio\\src\\main\\java\\img\\logo_oscuro.png")); // NOI18N
        jPanel16.add(jLabel62);
        jLabel62.setBounds(700, 10, 50, 40);

        jPanel4.add(jPanel16);
        jPanel16.setBounds(0, 0, 760, 60);

        groupBusquedaVentas.add(radioIDVentaVentas);
        radioIDVentaVentas.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        radioIDVentaVentas.setForeground(new java.awt.Color(0, 0, 0));
        radioIDVentaVentas.setText("ID Venta");
        jPanel4.add(radioIDVentaVentas);
        radioIDVentaVentas.setBounds(20, 80, 90, 21);

        groupBusquedaVentas.add(radioTodosVentas);
        radioTodosVentas.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        radioTodosVentas.setForeground(new java.awt.Color(0, 0, 0));
        radioTodosVentas.setSelected(true);
        radioTodosVentas.setText("Mostrar Todas las Ventas");
        jPanel4.add(radioTodosVentas);
        radioTodosVentas.setBounds(280, 180, 170, 21);

        cajaIDVentasBuscar.setBackground(new java.awt.Color(255, 255, 255));
        cajaIDVentasBuscar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jPanel4.add(cajaIDVentasBuscar);
        cajaIDVentasBuscar.setBounds(20, 110, 100, 18);

        comboVentasVehiculosBuscar.setBackground(new java.awt.Color(214, 198, 152));
        comboVentasVehiculosBuscar.setForeground(new java.awt.Color(0, 0, 0));
        jPanel4.add(comboVentasVehiculosBuscar);
        comboVentasVehiculosBuscar.setBounds(150, 180, 120, 26);

        groupBusquedaVentas.add(radioMesVentas);
        radioMesVentas.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        radioMesVentas.setForeground(new java.awt.Color(0, 0, 0));
        radioMesVentas.setText("Mes");
        jPanel4.add(radioMesVentas);
        radioMesVentas.setBounds(160, 80, 90, 21);

        comboVentasMesBuscar.setBackground(new java.awt.Color(214, 198, 152));
        comboVentasMesBuscar.setForeground(new java.awt.Color(0, 0, 0));
        jPanel4.add(comboVentasMesBuscar);
        comboVentasMesBuscar.setBounds(160, 110, 76, 26);

        groupBusquedaVentas.add(radioPrecioVentas);
        radioPrecioVentas.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        radioPrecioVentas.setForeground(new java.awt.Color(0, 0, 0));
        radioPrecioVentas.setText("Precio Menor A");
        jPanel4.add(radioPrecioVentas);
        radioPrecioVentas.setBounds(260, 80, 130, 21);

        comboVentasPrecioBuscar.setBackground(new java.awt.Color(214, 198, 152));
        comboVentasPrecioBuscar.setForeground(new java.awt.Color(0, 0, 0));
        jPanel4.add(comboVentasPrecioBuscar);
        comboVentasPrecioBuscar.setBounds(260, 110, 120, 26);

        groupBusquedaVentas.add(radioIdClienteVentas);
        radioIdClienteVentas.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        radioIdClienteVentas.setForeground(new java.awt.Color(0, 0, 0));
        radioIdClienteVentas.setText("ID Cliente");
        jPanel4.add(radioIdClienteVentas);
        radioIdClienteVentas.setBounds(550, 80, 100, 21);

        comboVentasClienteBuscar.setBackground(new java.awt.Color(214, 198, 152));
        comboVentasClienteBuscar.setForeground(new java.awt.Color(0, 0, 0));
        jPanel4.add(comboVentasClienteBuscar);
        comboVentasClienteBuscar.setBounds(550, 110, 120, 26);

        groupBusquedaVentas.add(radioIDEmpleadoVentas);
        radioIDEmpleadoVentas.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        radioIDEmpleadoVentas.setForeground(new java.awt.Color(0, 0, 0));
        radioIDEmpleadoVentas.setText("ID Empleado");
        jPanel4.add(radioIDEmpleadoVentas);
        radioIDEmpleadoVentas.setBounds(10, 150, 100, 21);

        comboVentasEmpleadoBuscar.setBackground(new java.awt.Color(214, 198, 152));
        comboVentasEmpleadoBuscar.setForeground(new java.awt.Color(0, 0, 0));
        jPanel4.add(comboVentasEmpleadoBuscar);
        comboVentasEmpleadoBuscar.setBounds(10, 180, 120, 26);

        groupBusquedaVentas.add(radioIDVehiculoVentas);
        radioIDVehiculoVentas.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        radioIDVehiculoVentas.setForeground(new java.awt.Color(0, 0, 0));
        radioIDVehiculoVentas.setText("ID Vehiculo");
        jPanel4.add(radioIDVehiculoVentas);
        radioIDVehiculoVentas.setBounds(160, 150, 100, 21);

        tablaVentas.setBackground(new java.awt.Color(214, 198, 152));
        tablaVentas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(tablaVentas);

        jPanel4.add(jScrollPane3);
        jScrollPane3.setBounds(20, 310, 720, 240);

        groupBusquedaVentas.add(radioVentasPagoBuscar);
        radioVentasPagoBuscar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        radioVentasPagoBuscar.setForeground(new java.awt.Color(0, 0, 0));
        radioVentasPagoBuscar.setText("Forma de Pago");
        jPanel4.add(radioVentasPagoBuscar);
        radioVentasPagoBuscar.setBounds(410, 80, 110, 21);

        comboVentasPagoBuscar.setBackground(new java.awt.Color(214, 198, 152));
        comboVentasPagoBuscar.setForeground(new java.awt.Color(0, 0, 0));
        jPanel4.add(comboVentasPagoBuscar);
        comboVentasPagoBuscar.setBounds(410, 110, 120, 26);

        internalVentas.getContentPane().add(jPanel4);
        jPanel4.setBounds(0, 0, 760, 580);

        jDesktopPane1.add(internalVentas);
        internalVentas.setBounds(0, 0, 770, 620);

        internalProximamente.setTitle("Proximamente");
        internalProximamente.setVisible(false);
        internalProximamente.getContentPane().setLayout(null);

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setLayout(null);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Estamos trabajando en la construcción de esta página");
        jPanel5.add(jLabel5);
        jLabel5.setBounds(60, 50, 640, 80);

        internalProximamente.getContentPane().add(jPanel5);
        jPanel5.setBounds(0, 0, 760, 580);

        jDesktopPane1.add(internalProximamente);
        internalProximamente.setBounds(0, 0, 770, 610);

        internalVehiculosEliminados.setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        internalVehiculosEliminados.setTitle("Historial de Vehiculos");
        internalVehiculosEliminados.setVisible(false);

        jPanel22.setBackground(new java.awt.Color(255, 255, 255));
        jPanel22.setLayout(null);

        jPanel23.setBackground(new java.awt.Color(214, 198, 152));
        jPanel23.setLayout(null);

        jLabel83.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel83.setForeground(new java.awt.Color(0, 0, 0));
        jLabel83.setText("Vehiculos Eliminados");
        jPanel23.add(jLabel83);
        jLabel83.setBounds(10, 10, 140, 30);

        jLabel84.setIcon(new javax.swing.ImageIcon("C:\\Users\\eduar\\Documents\\ITSJ\\5. Quinto Semestre\\Taller de bases de datos\\Proyecto final\\Proyecto_Final_TBD_Escritorio\\src\\main\\java\\img\\logo_oscuro.png")); // NOI18N
        jPanel23.add(jLabel84);
        jLabel84.setBounds(360, 0, 50, 50);

        jPanel22.add(jPanel23);
        jPanel23.setBounds(0, 0, 410, 50);

        tablaVehiculosEliminados.setBackground(new java.awt.Color(247, 227, 178));
        tablaVehiculosEliminados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane4.setViewportView(tablaVehiculosEliminados);

        jPanel22.add(jScrollPane4);
        jScrollPane4.setBounds(10, 60, 390, 220);

        btnVehiculosEliminadosCerrar.setBackground(new java.awt.Color(227, 211, 163));
        btnVehiculosEliminadosCerrar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnVehiculosEliminadosCerrar.setForeground(new java.awt.Color(0, 0, 0));
        btnVehiculosEliminadosCerrar.setText("Cerrar Ventana");
        btnVehiculosEliminadosCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVehiculosEliminadosCerrarActionPerformed(evt);
            }
        });
        jPanel22.add(btnVehiculosEliminadosCerrar);
        btnVehiculosEliminadosCerrar.setBounds(130, 310, 140, 50);

        javax.swing.GroupLayout internalVehiculosEliminadosLayout = new javax.swing.GroupLayout(internalVehiculosEliminados.getContentPane());
        internalVehiculosEliminados.getContentPane().setLayout(internalVehiculosEliminadosLayout);
        internalVehiculosEliminadosLayout.setHorizontalGroup(
            internalVehiculosEliminadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel22, javax.swing.GroupLayout.DEFAULT_SIZE, 408, Short.MAX_VALUE)
        );
        internalVehiculosEliminadosLayout.setVerticalGroup(
            internalVehiculosEliminadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel22, javax.swing.GroupLayout.DEFAULT_SIZE, 404, Short.MAX_VALUE)
        );

        jDesktopPane1.add(internalVehiculosEliminados);
        internalVehiculosEliminados.setBounds(120, 40, 420, 440);

        bg.add(jDesktopPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 0, 770, 610));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(bg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

   
 
    
    // ============================================== VENTANA VEHICULOS ================================================================
    
    private void btnCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarSesionActionPerformed


        
        
        SwingUtilities.invokeLater(new Runnable() {

            @Override
            public void run() {

                new VentanaLogin();

            }
        });
        
        setVisible(false);
        
    }//GEN-LAST:event_btnCerrarSesionActionPerformed

    private void btnHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHomeActionPerformed
        
        nav.marcarBotonActivo(btnHome, btnVehiculos, btnModelos, btnVentas, btnClientes, btnEmpleados, btnDocumentacion);
        
        nav.mostrarPanel(internalHome, internalVehiculos, internalModelos, internalVentas, internalProximamente, internalVehiculosEliminados);
        

       
    }//GEN-LAST:event_btnHomeActionPerformed

    private void btnVehiculosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVehiculosActionPerformed

        nav.marcarBotonActivo(btnVehiculos, btnHome, btnModelos, btnVentas, btnClientes, btnEmpleados, btnDocumentacion);
        
         nav.mostrarPanel(internalVehiculos, internalHome, internalModelos, internalVentas, internalProximamente, internalVehiculosEliminados);
        
    }//GEN-LAST:event_btnVehiculosActionPerformed

    private void btnModelosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModelosActionPerformed

        nav.marcarBotonActivo(btnModelos, btnVehiculos, btnHome, btnVentas, btnClientes, btnEmpleados, btnDocumentacion);
        
         nav.mostrarPanel(internalModelos, internalVehiculos, internalHome, internalVentas, internalProximamente, internalVehiculosEliminados);
        
    }//GEN-LAST:event_btnModelosActionPerformed

    private void btnVentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVentasActionPerformed

        nav.marcarBotonActivo(btnVentas, btnVehiculos, btnHome, btnModelos, btnClientes, btnEmpleados, btnDocumentacion);
        
         nav.mostrarPanel(internalVentas, internalVehiculos, internalModelos, internalHome, internalProximamente, internalVehiculosEliminados);
        
    }//GEN-LAST:event_btnVentasActionPerformed

    private void btnEmpleadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEmpleadosActionPerformed

        nav.marcarBotonActivo(btnEmpleados, btnVehiculos, btnHome, btnModelos, btnVentas, btnClientes, btnDocumentacion);
        
         nav.mostrarPanel(internalProximamente, internalVehiculos, internalModelos, internalVentas, internalHome, internalVehiculosEliminados);
        
    }//GEN-LAST:event_btnEmpleadosActionPerformed

    private void btnClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClientesActionPerformed
        

        nav.marcarBotonActivo(btnClientes, btnVehiculos, btnHome, btnModelos, btnVentas, btnEmpleados, btnDocumentacion);
        
         nav.mostrarPanel(internalProximamente, internalVehiculos, internalModelos, internalVentas, internalHome, internalVehiculosEliminados);
        
    }//GEN-LAST:event_btnClientesActionPerformed

    private void btnDocumentacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDocumentacionActionPerformed
        
 
        nav.marcarBotonActivo(btnDocumentacion, btnVehiculos, btnHome, btnModelos, btnVentas, btnEmpleados, btnClientes);
        
        nav.mostrarPanel(internalProximamente, internalVehiculos, internalModelos, internalVentas, internalHome, internalVehiculosEliminados);
        
    }//GEN-LAST:event_btnDocumentacionActionPerformed

    
    
    
    private void rformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rformed


     

        
    }//GEN-LAST:event_rformed

    private void cajaNombreModeloBusquedaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cajaNombreModeloBusquedaKeyReleased

 
        
    }//GEN-LAST:event_cajaNombreModeloBusquedaKeyReleased

    
    
    
    private void btnVehiculosEliminadosCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVehiculosEliminadosCerrarActionPerformed
        
        internalVehiculosEliminados.setVisible(false);
        
    }//GEN-LAST:event_btnVehiculosEliminadosCerrarActionPerformed

    // =============================== Acciones Tabla modelos =======================
    
    private void tablaVehiculosMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaVehiculosMouseReleased

        String nc = (String) tablaVehiculos.getValueAt(tablaVehiculos.getSelectedRow(), 0);
        
        cajaNumVehiculoBuscar.setText(nc);
        
        
        
        // TODO add your handling code here:
    }//GEN-LAST:event_tablaVehiculosMouseReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new VentanaInicio().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bg;
    private javax.swing.JButton btnActualizarModelos;
    private javax.swing.JButton btnActualizarVentas;
    private javax.swing.JButton btnAgregarModelos;
    private javax.swing.JButton btnAgregarVehiculos;
    private javax.swing.JButton btnAgregarVentas;
    private javax.swing.JButton btnCerrarSesion;
    private javax.swing.JButton btnClientes;
    private javax.swing.JButton btnDocumentacion;
    private javax.swing.JButton btnEliminarModelos;
    private javax.swing.JButton btnEliminarVehiculos;
    private javax.swing.JButton btnEliminarVentas;
    private javax.swing.JButton btnEmpleados;
    private javax.swing.JButton btnHome;
    private javax.swing.JButton btnHomeGrafica;
    private javax.swing.JButton btnHomeHistorialPrecios;
    private javax.swing.JButton btnHomeReporte;
    private javax.swing.JButton btnHomeVehiculosEliminados;
    private javax.swing.JButton btnHomeVista;
    private javax.swing.JButton btnModelos;
    private javax.swing.JButton btnModificarVehiculos;
    private javax.swing.JButton btnVehiculos;
    private javax.swing.JButton btnVehiculosEliminadosCerrar;
    private javax.swing.JButton btnVentas;
    private javax.swing.JTextField cajaFabricanteModeloBusqueda;
    private javax.swing.JTextField cajaIDModeloBusqueda;
    private javax.swing.JTextField cajaIDVentasBuscar;
    private javax.swing.JTextField cajaModeloPasajerosBusqueda;
    private javax.swing.JTextField cajaModeloPesoBusqueda;
    private javax.swing.JTextField cajaModeloPuertasBusqueda;
    private javax.swing.JTextField cajaNombreModeloBusqueda;
    private javax.swing.JTextField cajaNumSerieBuscar;
    private javax.swing.JTextField cajaNumVehiculoBuscar;
    private javax.swing.JTextField cajaPaisModeloBusqueda;
    private javax.swing.JComboBox<String> comboAnioBusqueda1;
    private javax.swing.JComboBox<String> comboAnioModeloBuscar;
    private javax.swing.JComboBox<String> comboEstadoBusqueda;
    private javax.swing.JComboBox<String> comboModeloBusqueda;
    private javax.swing.JComboBox<String> comboNumeroCilindrosBuscar;
    private javax.swing.JComboBox<String> comboPrecioBusqueda1;
    private javax.swing.JComboBox<String> comboTipoBusqueda;
    private javax.swing.JComboBox<String> comboVentasClienteBuscar;
    private javax.swing.JComboBox<String> comboVentasEmpleadoBuscar;
    private javax.swing.JComboBox<String> comboVentasMesBuscar;
    private javax.swing.JComboBox<String> comboVentasPagoBuscar;
    private javax.swing.JComboBox<String> comboVentasPrecioBuscar;
    private javax.swing.JComboBox<String> comboVentasVehiculosBuscar;
    private javax.swing.ButtonGroup groupBusquedaModelos;
    private javax.swing.ButtonGroup groupBusquedaVehiculos;
    private javax.swing.ButtonGroup groupBusquedaVentas;
    private javax.swing.JInternalFrame internalHome;
    private javax.swing.JInternalFrame internalModelos;
    private javax.swing.JInternalFrame internalProximamente;
    private javax.swing.JInternalFrame internalVehiculos;
    private javax.swing.JInternalFrame internalVehiculosEliminados;
    private javax.swing.JInternalFrame internalVentas;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel62;
    private javax.swing.JLabel jLabel81;
    private javax.swing.JLabel jLabel82;
    private javax.swing.JLabel jLabel83;
    private javax.swing.JLabel jLabel84;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel21;
    private javax.swing.JPanel jPanel22;
    private javax.swing.JPanel jPanel23;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JRadioButton radioAnioBusqueda1;
    private javax.swing.JRadioButton radioAnioModeloBuscar;
    private javax.swing.JRadioButton radioEstadoBusqueda1;
    private javax.swing.JRadioButton radioFabricanteModelo;
    private javax.swing.JRadioButton radioIDEmpleadoVentas;
    private javax.swing.JRadioButton radioIDVehiculoVentas;
    private javax.swing.JRadioButton radioIDVentaVentas;
    private javax.swing.JRadioButton radioIdClienteVentas;
    private javax.swing.JRadioButton radioMesVentas;
    private javax.swing.JRadioButton radioModeloBusqueda;
    private javax.swing.JRadioButton radioNombreModelo;
    private javax.swing.JRadioButton radioNumSerieBusqueda;
    private javax.swing.JRadioButton radioNumVehiculoBusqueda;
    private javax.swing.JRadioButton radioNumeroCilindros;
    private javax.swing.JRadioButton radioNumeroPuertas;
    private javax.swing.JRadioButton radioPais;
    private javax.swing.JRadioButton radioPasajeros;
    private javax.swing.JRadioButton radioPeso;
    private javax.swing.JRadioButton radioPrecioBusqueda1;
    private javax.swing.JRadioButton radioPrecioVentas;
    private javax.swing.JRadioButton radioTipoBusqueda;
    private javax.swing.JRadioButton radioTodosBusqueda;
    private javax.swing.JRadioButton radioTodosModelos;
    private javax.swing.JRadioButton radioTodosVentas;
    private javax.swing.JRadioButton radioVentasPagoBuscar;
    private javax.swing.JRadioButton radioidModeloBusqueda;
    private javax.swing.JPanel sidePane;
    private javax.swing.JTable tablaModelos;
    private javax.swing.JTable tablaVehiculos;
    private javax.swing.JTable tablaVehiculosEliminados;
    private javax.swing.JTable tablaVentas;
    // End of variables declaration//GEN-END:variables
}
