/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UI;




import Modelo.Modelo;
import util.ComboBoxUtil;
import Repository.ModeloRepository;
import Service.IModeloService;
import Service.ModeloService;
import UI.tabla.ButtonEditor;
import UI.tabla.ButtonRenderer;
import java.sql.ResultSet;
import java.time.LocalDate;
import java.util.Arrays;
import java.util.List;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;




public class VentanaInicio extends javax.swing.JFrame{
    
    private final IModeloService modeloService = new ModeloService(new ModeloRepository());
   
    private NavegacionController nav = new NavegacionController();
    
    LocalDate hoy = LocalDate.now();
    
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VentanaInicio.class.getName());

    /**
     * Creates new form VentanaInicio
     */
    public VentanaInicio() {
        initComponents();
        setVisible(true);
        setLocationRelativeTo(null);
        internalHome.setVisible(true);
        internalVehiculos.setVisible(false);
        internalModelos.setVisible(false);
        internalVentas.setVisible(false);
        internalProximamente.setVisible(false);

       
        
        pack();
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        groupBusquedaVehiculos = new javax.swing.ButtonGroup();
        groupBusquedaModelos = new javax.swing.ButtonGroup();
        groupBusquedaVentas = new javax.swing.ButtonGroup();
        bg = new javax.swing.JPanel();
        sidePane = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        btnCerrarSesion = new javax.swing.JButton();
        btnHome = new javax.swing.JButton();
        btnVehiculos = new javax.swing.JButton();
        btnModelos = new javax.swing.JButton();
        btnVentas = new javax.swing.JButton();
        btnEmpleados = new javax.swing.JButton();
        btnClientes = new javax.swing.JButton();
        btnDocumentacion = new javax.swing.JButton();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        internalHome = new javax.swing.JInternalFrame();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel81 = new javax.swing.JLabel();
        jPanel21 = new javax.swing.JPanel();
        jLabel82 = new javax.swing.JLabel();
        btnHomeGrafica = new javax.swing.JButton();
        btnHomeVista = new javax.swing.JButton();
        btnHomeReporte = new javax.swing.JButton();
        btnHomeHistorialPrecios = new javax.swing.JButton();
        btnHomeVehiculosEliminados = new javax.swing.JButton();
        internalVehiculos = new javax.swing.JInternalFrame();
        jPanel2 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btnModificarVehiculos = new javax.swing.JButton();
        btnAgregarVehiculos = new javax.swing.JButton();
        btnEliminarVehiculos = new javax.swing.JButton();
        cajaNumVehiculoBuscar = new javax.swing.JTextField();
        radioTipoBusqueda = new javax.swing.JRadioButton();
        radioModeloBusqueda = new javax.swing.JRadioButton();
        cajaNumSerieBuscar = new javax.swing.JTextField();
        comboModeloBusqueda = new javax.swing.JComboBox<>();
        radioNumSerieBusqueda = new javax.swing.JRadioButton();
        comboEstadoBusqueda = new javax.swing.JComboBox<>();
        radioNumVehiculoBusqueda = new javax.swing.JRadioButton();
        comboTipoBusqueda = new javax.swing.JComboBox<>();
        radioTodosBusqueda = new javax.swing.JRadioButton();
        radioPrecioBusqueda1 = new javax.swing.JRadioButton();
        comboPrecioBusqueda1 = new javax.swing.JComboBox<>();
        radioAnioBusqueda1 = new javax.swing.JRadioButton();
        comboAnioBusqueda1 = new javax.swing.JComboBox<>();
        radioEstadoBusqueda1 = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaVehiculos = new javax.swing.JTable();
        internalModelos = new javax.swing.JInternalFrame();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaModelos = new javax.swing.JTable();
        jPanel11 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        btnEliminarModelos = new javax.swing.JButton();
        btnAgregarModelos = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        btnActualizarModelos = new javax.swing.JButton();
        jLabel23 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        internalVentas = new javax.swing.JInternalFrame();
        jPanel4 = new javax.swing.JPanel();
        jPanel16 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        btnEliminarVentas = new javax.swing.JButton();
        btnAgregarVentas = new javax.swing.JButton();
        btnActualizarVentas = new javax.swing.JButton();
        jLabel62 = new javax.swing.JLabel();
        radioIDVentaVentas = new javax.swing.JRadioButton();
        radioTodosVentas = new javax.swing.JRadioButton();
        cajaIDVentasBuscar = new javax.swing.JTextField();
        comboVentasVehiculosBuscar = new javax.swing.JComboBox<>();
        radioMesVentas = new javax.swing.JRadioButton();
        comboVentasMesBuscar = new javax.swing.JComboBox<>();
        radioPrecioVentas = new javax.swing.JRadioButton();
        comboVentasPrecioBuscar = new javax.swing.JComboBox<>();
        radioIdClienteVentas = new javax.swing.JRadioButton();
        comboVentasClienteBuscar = new javax.swing.JComboBox<>();
        radioIDEmpleadoVentas = new javax.swing.JRadioButton();
        comboVentasEmpleadoBuscar = new javax.swing.JComboBox<>();
        radioIDVehiculoVentas = new javax.swing.JRadioButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tablaVentas = new javax.swing.JTable();
        radioVentasPagoBuscar = new javax.swing.JRadioButton();
        comboVentasPagoBuscar = new javax.swing.JComboBox<>();
        internalProximamente = new javax.swing.JInternalFrame();
        jPanel5 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        internalVehiculosEliminados = new javax.swing.JInternalFrame();
        jPanel22 = new javax.swing.JPanel();
        jPanel23 = new javax.swing.JPanel();
        jLabel83 = new javax.swing.JLabel();
        jLabel84 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tablaVehiculosEliminados = new javax.swing.JTable();
        btnVehiculosEliminadosCerrar = new javax.swing.JButton();
        internalAgregarModelos = new javax.swing.JInternalFrame();
        jPanel12 = new javax.swing.JPanel();
        jPanel13 = new javax.swing.JPanel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        jLabel49 = new javax.swing.JLabel();
        cajaModelosPaisAgregar = new javax.swing.JTextField();
        cajaModelosNombreAgregar = new javax.swing.JTextField();
        cajaModelosFabricanteAgregar = new javax.swing.JTextField();
        cajaModelosColorAgregar = new javax.swing.JTextField();
        comboModelosCilindrosAgregar = new javax.swing.JComboBox<>();
        comboModelosAnioAgregar = new javax.swing.JComboBox<>();
        btnModelosCancelarAgregar = new javax.swing.JButton();
        btnModelosAgregarAgregar = new javax.swing.JButton();
        btnModelosRestaurarAgregar = new javax.swing.JButton();
        cajaModelosPasajerosAgregar = new javax.swing.JTextField();
        cajaModelosPuertasAgregar = new javax.swing.JTextField();
        cajaModelosPesoAgregar = new javax.swing.JTextField();
        internalCambiosModelos = new javax.swing.JInternalFrame();
        jPanel14 = new javax.swing.JPanel();
        jPanel15 = new javax.swing.JPanel();
        jLabel50 = new javax.swing.JLabel();
        jLabel51 = new javax.swing.JLabel();
        jLabel52 = new javax.swing.JLabel();
        jLabel53 = new javax.swing.JLabel();
        jLabel54 = new javax.swing.JLabel();
        jLabel55 = new javax.swing.JLabel();
        jLabel56 = new javax.swing.JLabel();
        jLabel57 = new javax.swing.JLabel();
        jLabel58 = new javax.swing.JLabel();
        jLabel59 = new javax.swing.JLabel();
        jLabel60 = new javax.swing.JLabel();
        jLabel61 = new javax.swing.JLabel();
        cajaModelosPaisActualizar = new javax.swing.JTextField();
        cajaModelosNombreActualizar = new javax.swing.JTextField();
        cajaModelosFabricanteActualizar = new javax.swing.JTextField();
        cajaModelosColorActualizar = new javax.swing.JTextField();
        comboModelosCilindrosActualizar = new javax.swing.JComboBox<>();
        comboModelosAnioActualizar = new javax.swing.JComboBox<>();
        btnModelosCancelarActualizar = new javax.swing.JButton();
        btnModelosActualizarActualizar = new javax.swing.JButton();
        cajaModelosPasajerosActualizar = new javax.swing.JTextField();
        cajaModelosPuertasActualizar = new javax.swing.JTextField();
        cajaModelosPesoActualizar = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Autos Amistosos");
        setResizable(false);

        bg.setBackground(new java.awt.Color(255, 255, 255));
        bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        sidePane.setBackground(Colores.COLOR_PRINCIPAL);
        sidePane.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel13.setIcon(new javax.swing.ImageIcon("C:\\Users\\eduar\\Documents\\ITSJ\\5. Quinto Semestre\\Taller de bases de datos\\Proyecto final\\Proyecto_Final_TBD_Escritorio\\src\\main\\java\\img\\LOGO_chico.png")); // NOI18N
        sidePane.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, 140, 140));

        btnCerrarSesion.setBackground(new java.awt.Color(227, 211, 163));
        btnCerrarSesion.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnCerrarSesion.setForeground(new java.awt.Color(0, 0, 0));
        btnCerrarSesion.setIcon(new javax.swing.ImageIcon("C:\\Users\\eduar\\Documents\\ITSJ\\5. Quinto Semestre\\Taller de bases de datos\\Proyecto final\\Proyecto_Final_TBD_Escritorio\\src\\main\\java\\img\\cerrar_sesion.png")); // NOI18N
        btnCerrarSesion.setText("Cerrar Sesión");
        btnCerrarSesion.setToolTipText("");
        btnCerrarSesion.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnCerrarSesion.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnCerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarSesionActionPerformed(evt);
            }
        });
        sidePane.add(btnCerrarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 420, 220, 40));

        btnHome.setBackground(new java.awt.Color(214, 198, 152));
        btnHome.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnHome.setForeground(new java.awt.Color(0, 0, 0));
        btnHome.setIcon(new javax.swing.ImageIcon("C:\\Users\\eduar\\Documents\\ITSJ\\6. Sexto Semestre\\Administración de Bases de Datos\\Proyecto Final\\Proyecto_Final_ABD_AutosAmistosos\\src\\main\\java\\img\\home.png")); // NOI18N
        btnHome.setText("Home");
        btnHome.setToolTipText("");
        btnHome.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnHome.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHomeActionPerformed(evt);
            }
        });
        sidePane.add(btnHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 220, 40));

        btnVehiculos.setBackground(new java.awt.Color(227, 211, 163));
        btnVehiculos.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnVehiculos.setForeground(new java.awt.Color(0, 0, 0));
        btnVehiculos.setIcon(new javax.swing.ImageIcon("C:\\Users\\eduar\\Documents\\ITSJ\\5. Quinto Semestre\\Taller de bases de datos\\Proyecto final\\Proyecto_Final_TBD_Escritorio\\src\\main\\java\\img\\carro.png")); // NOI18N
        btnVehiculos.setText("Vehículos");
        btnVehiculos.setToolTipText("");
        btnVehiculos.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnVehiculos.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnVehiculos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVehiculosActionPerformed(evt);
            }
        });
        sidePane.add(btnVehiculos, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 220, 40));

        btnModelos.setBackground(new java.awt.Color(227, 211, 163));
        btnModelos.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnModelos.setForeground(new java.awt.Color(0, 0, 0));
        btnModelos.setIcon(new javax.swing.ImageIcon("C:\\Users\\eduar\\Documents\\ITSJ\\5. Quinto Semestre\\Taller de bases de datos\\Proyecto final\\Proyecto_Final_TBD_Escritorio\\src\\main\\java\\img\\modelo.png")); // NOI18N
        btnModelos.setText("Modelos");
        btnModelos.setToolTipText("");
        btnModelos.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnModelos.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnModelos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModelosActionPerformed(evt);
            }
        });
        sidePane.add(btnModelos, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 220, 220, 40));

        btnVentas.setBackground(new java.awt.Color(227, 211, 163));
        btnVentas.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnVentas.setForeground(new java.awt.Color(0, 0, 0));
        btnVentas.setIcon(new javax.swing.ImageIcon("C:\\Users\\eduar\\Documents\\ITSJ\\5. Quinto Semestre\\Taller de bases de datos\\Proyecto final\\Proyecto_Final_TBD_Escritorio\\src\\main\\java\\img\\ventas.png")); // NOI18N
        btnVentas.setText("Ventas");
        btnVentas.setToolTipText("");
        btnVentas.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnVentas.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnVentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVentasActionPerformed(evt);
            }
        });
        sidePane.add(btnVentas, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, 220, 40));

        btnEmpleados.setBackground(new java.awt.Color(227, 211, 163));
        btnEmpleados.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnEmpleados.setForeground(new java.awt.Color(0, 0, 0));
        btnEmpleados.setIcon(new javax.swing.ImageIcon("C:\\Users\\eduar\\Documents\\ITSJ\\5. Quinto Semestre\\Taller de bases de datos\\Proyecto final\\Proyecto_Final_TBD_Escritorio\\src\\main\\java\\img\\empleados.png")); // NOI18N
        btnEmpleados.setText("Empleados");
        btnEmpleados.setToolTipText("");
        btnEmpleados.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnEmpleados.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnEmpleados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEmpleadosActionPerformed(evt);
            }
        });
        sidePane.add(btnEmpleados, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 300, 220, 40));

        btnClientes.setBackground(new java.awt.Color(227, 211, 163));
        btnClientes.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnClientes.setForeground(new java.awt.Color(0, 0, 0));
        btnClientes.setIcon(new javax.swing.ImageIcon("C:\\Users\\eduar\\Documents\\ITSJ\\5. Quinto Semestre\\Taller de bases de datos\\Proyecto final\\Proyecto_Final_TBD_Escritorio\\src\\main\\java\\img\\cliente.png")); // NOI18N
        btnClientes.setText("Clientes");
        btnClientes.setToolTipText("");
        btnClientes.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnClientes.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClientesActionPerformed(evt);
            }
        });
        sidePane.add(btnClientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 340, 220, 40));

        btnDocumentacion.setBackground(new java.awt.Color(227, 211, 163));
        btnDocumentacion.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnDocumentacion.setForeground(new java.awt.Color(0, 0, 0));
        btnDocumentacion.setIcon(new javax.swing.ImageIcon("C:\\Users\\eduar\\Documents\\ITSJ\\5. Quinto Semestre\\Taller de bases de datos\\Proyecto final\\Proyecto_Final_TBD_Escritorio\\src\\main\\java\\img\\documento.png")); // NOI18N
        btnDocumentacion.setText("Documentación");
        btnDocumentacion.setToolTipText("");
        btnDocumentacion.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnDocumentacion.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnDocumentacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDocumentacionActionPerformed(evt);
            }
        });
        sidePane.add(btnDocumentacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 380, 220, 40));

        bg.add(sidePane, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 221, 615));

        internalHome.setBackground(new java.awt.Color(255, 255, 255));
        internalHome.setTitle("Home");
        internalHome.setToolTipText("");
        internalHome.setVisible(false);
        internalHome.getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(247, 227, 178));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Hola Bienvenido a Autos Amistosos");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(190, 0, 370, 66);

        jLabel81.setIcon(new javax.swing.ImageIcon("C:\\Users\\eduar\\Documents\\ITSJ\\5. Quinto Semestre\\Taller de bases de datos\\Proyecto final\\Proyecto_Final_TBD_Escritorio\\src\\main\\java\\img\\LOGO.png")); // NOI18N
        jPanel1.add(jLabel81);
        jLabel81.setBounds(270, 50, 200, 190);

        jPanel21.setBackground(new java.awt.Color(255, 255, 255));
        jPanel21.setLayout(null);

        jLabel82.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel82.setForeground(new java.awt.Color(0, 0, 0));
        jLabel82.setText("Acciones Rápidas");
        jPanel21.add(jLabel82);
        jLabel82.setBounds(10, 10, 150, 30);

        btnHomeGrafica.setBackground(new java.awt.Color(227, 211, 163));
        btnHomeGrafica.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnHomeGrafica.setForeground(new java.awt.Color(0, 0, 0));
        btnHomeGrafica.setIcon(new javax.swing.ImageIcon("C:\\Users\\eduar\\Documents\\ITSJ\\5. Quinto Semestre\\Taller de bases de datos\\Proyecto final\\Proyecto_Final_TBD_Escritorio\\src\\main\\java\\img\\grafica.png")); // NOI18N
        btnHomeGrafica.setText("Gráfica Ventas");
        jPanel21.add(btnHomeGrafica);
        btnHomeGrafica.setBounds(540, 70, 200, 60);

        btnHomeVista.setBackground(new java.awt.Color(227, 211, 163));
        btnHomeVista.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnHomeVista.setForeground(new java.awt.Color(0, 0, 0));
        btnHomeVista.setIcon(new javax.swing.ImageIcon("C:\\Users\\eduar\\Documents\\ITSJ\\5. Quinto Semestre\\Taller de bases de datos\\Proyecto final\\Proyecto_Final_TBD_Escritorio\\src\\main\\java\\img\\vista.png")); // NOI18N
        btnHomeVista.setText("Vista Vehículos-Modelo");
        btnHomeVista.setToolTipText("");
        jPanel21.add(btnHomeVista);
        btnHomeVista.setBounds(10, 70, 240, 60);

        btnHomeReporte.setBackground(new java.awt.Color(227, 211, 163));
        btnHomeReporte.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnHomeReporte.setForeground(new java.awt.Color(0, 0, 0));
        btnHomeReporte.setIcon(new javax.swing.ImageIcon("C:\\Users\\eduar\\Documents\\ITSJ\\5. Quinto Semestre\\Taller de bases de datos\\Proyecto final\\Proyecto_Final_TBD_Escritorio\\src\\main\\java\\img\\reporte.png")); // NOI18N
        btnHomeReporte.setText("Reporte Ventas");
        jPanel21.add(btnHomeReporte);
        btnHomeReporte.setBounds(290, 70, 210, 60);

        btnHomeHistorialPrecios.setBackground(new java.awt.Color(227, 211, 163));
        btnHomeHistorialPrecios.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnHomeHistorialPrecios.setForeground(new java.awt.Color(0, 0, 0));
        btnHomeHistorialPrecios.setIcon(new javax.swing.ImageIcon("C:\\Users\\eduar\\Documents\\ITSJ\\5. Quinto Semestre\\Taller de bases de datos\\Proyecto final\\Proyecto_Final_TBD_Escritorio\\src\\main\\java\\img\\ventas.png")); // NOI18N
        btnHomeHistorialPrecios.setText("Historial Precios");
        btnHomeHistorialPrecios.setToolTipText("");
        jPanel21.add(btnHomeHistorialPrecios);
        btnHomeHistorialPrecios.setBounds(450, 180, 240, 60);

        btnHomeVehiculosEliminados.setBackground(new java.awt.Color(227, 211, 163));
        btnHomeVehiculosEliminados.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnHomeVehiculosEliminados.setForeground(new java.awt.Color(0, 0, 0));
        btnHomeVehiculosEliminados.setIcon(new javax.swing.ImageIcon("C:\\Users\\eduar\\Documents\\ITSJ\\5. Quinto Semestre\\Taller de bases de datos\\Proyecto final\\Proyecto_Final_TBD_Escritorio\\src\\main\\java\\img\\carro.png")); // NOI18N
        btnHomeVehiculosEliminados.setText("Vehículos Eliminados");
        btnHomeVehiculosEliminados.setToolTipText("");
        jPanel21.add(btnHomeVehiculosEliminados);
        btnHomeVehiculosEliminados.setBounds(90, 180, 240, 60);

        jPanel1.add(jPanel21);
        jPanel21.setBounds(0, 240, 760, 330);

        internalHome.getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 760, 570);

        jDesktopPane1.add(internalHome);
        internalHome.setBounds(0, 0, 770, 610);

        internalVehiculos.setTitle("Vehiculos");
        internalVehiculos.setVisible(false);
        internalVehiculos.getContentPane().setLayout(null);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(null);

        jPanel6.setBackground(new java.awt.Color(214, 198, 152));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Vehículos");

        jLabel6.setIcon(new javax.swing.ImageIcon("C:\\Users\\eduar\\Documents\\ITSJ\\5. Quinto Semestre\\Taller de bases de datos\\Proyecto final\\Proyecto_Final_TBD_Escritorio\\src\\main\\java\\img\\logo_oscuro.png")); // NOI18N

        btnModificarVehiculos.setBackground(new java.awt.Color(227, 211, 163));
        btnModificarVehiculos.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnModificarVehiculos.setForeground(new java.awt.Color(0, 0, 0));
        btnModificarVehiculos.setIcon(new javax.swing.ImageIcon("C:\\Users\\eduar\\Documents\\ITSJ\\5. Quinto Semestre\\Taller de bases de datos\\Proyecto final\\Proyecto_Final_TBD_Escritorio\\src\\main\\java\\img\\actualizar.png")); // NOI18N
        btnModificarVehiculos.setText("Actualizar");
        btnModificarVehiculos.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        btnModificarVehiculos.setEnabled(false);

        btnAgregarVehiculos.setBackground(new java.awt.Color(227, 211, 163));
        btnAgregarVehiculos.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnAgregarVehiculos.setForeground(new java.awt.Color(0, 0, 0));
        btnAgregarVehiculos.setIcon(new javax.swing.ImageIcon("C:\\Users\\eduar\\Documents\\ITSJ\\5. Quinto Semestre\\Taller de bases de datos\\Proyecto final\\Proyecto_Final_TBD_Escritorio\\src\\main\\java\\img\\agregar.png")); // NOI18N
        btnAgregarVehiculos.setText("Agregar");
        btnAgregarVehiculos.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        btnEliminarVehiculos.setBackground(new java.awt.Color(227, 211, 163));
        btnEliminarVehiculos.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnEliminarVehiculos.setForeground(new java.awt.Color(0, 0, 0));
        btnEliminarVehiculos.setIcon(new javax.swing.ImageIcon("C:\\Users\\eduar\\Documents\\ITSJ\\5. Quinto Semestre\\Taller de bases de datos\\Proyecto final\\Proyecto_Final_TBD_Escritorio\\src\\main\\java\\img\\eliminar.png")); // NOI18N
        btnEliminarVehiculos.setText("Eliminar");
        btnEliminarVehiculos.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        btnEliminarVehiculos.setEnabled(false);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 204, Short.MAX_VALUE)
                .addComponent(btnAgregarVehiculos, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnModificarVehiculos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnEliminarVehiculos)
                .addGap(43, 43, 43)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnAgregarVehiculos, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnEliminarVehiculos, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnModificarVehiculos, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.add(jPanel6);
        jPanel6.setBounds(0, 0, 760, 60);

        cajaNumVehiculoBuscar.setBackground(new java.awt.Color(255, 255, 255));
        cajaNumVehiculoBuscar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jPanel2.add(cajaNumVehiculoBuscar);
        cajaNumVehiculoBuscar.setBounds(30, 100, 210, 30);

        groupBusquedaVehiculos.add(radioTipoBusqueda);
        radioTipoBusqueda.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        radioTipoBusqueda.setForeground(new java.awt.Color(0, 0, 0));
        radioTipoBusqueda.setText("Tipo");
        jPanel2.add(radioTipoBusqueda);
        radioTipoBusqueda.setBounds(510, 150, 200, 25);

        groupBusquedaVehiculos.add(radioModeloBusqueda);
        radioModeloBusqueda.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        radioModeloBusqueda.setForeground(new java.awt.Color(0, 0, 0));
        radioModeloBusqueda.setText("Modelo");
        jPanel2.add(radioModeloBusqueda);
        radioModeloBusqueda.setBounds(510, 70, 170, 25);

        cajaNumSerieBuscar.setBackground(new java.awt.Color(255, 255, 255));
        cajaNumSerieBuscar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jPanel2.add(cajaNumSerieBuscar);
        cajaNumSerieBuscar.setBounds(270, 100, 210, 30);

        comboModeloBusqueda.setBackground(new java.awt.Color(214, 198, 152));
        comboModeloBusqueda.setForeground(new java.awt.Color(0, 0, 0));
        jPanel2.add(comboModeloBusqueda);
        comboModeloBusqueda.setBounds(510, 100, 210, 26);

        groupBusquedaVehiculos.add(radioNumSerieBusqueda);
        radioNumSerieBusqueda.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        radioNumSerieBusqueda.setForeground(new java.awt.Color(0, 0, 0));
        radioNumSerieBusqueda.setText("Número de Serie");
        jPanel2.add(radioNumSerieBusqueda);
        radioNumSerieBusqueda.setBounds(260, 70, 170, 25);

        comboEstadoBusqueda.setBackground(new java.awt.Color(214, 198, 152));
        comboEstadoBusqueda.setForeground(new java.awt.Color(0, 0, 0));
        jPanel2.add(comboEstadoBusqueda);
        comboEstadoBusqueda.setBounds(30, 250, 210, 26);

        groupBusquedaVehiculos.add(radioNumVehiculoBusqueda);
        radioNumVehiculoBusqueda.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        radioNumVehiculoBusqueda.setForeground(new java.awt.Color(0, 0, 0));
        radioNumVehiculoBusqueda.setText("Número de Vehículo");
        jPanel2.add(radioNumVehiculoBusqueda);
        radioNumVehiculoBusqueda.setBounds(30, 70, 170, 25);

        comboTipoBusqueda.setBackground(new java.awt.Color(214, 198, 152));
        comboTipoBusqueda.setForeground(new java.awt.Color(0, 0, 0));
        jPanel2.add(comboTipoBusqueda);
        comboTipoBusqueda.setBounds(510, 180, 210, 26);

        groupBusquedaVehiculos.add(radioTodosBusqueda);
        radioTodosBusqueda.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        radioTodosBusqueda.setForeground(new java.awt.Color(0, 0, 0));
        radioTodosBusqueda.setSelected(true);
        radioTodosBusqueda.setText("Mostrar Todos los Vehículos");
        jPanel2.add(radioTodosBusqueda);
        radioTodosBusqueda.setBounds(290, 240, 230, 25);

        groupBusquedaVehiculos.add(radioPrecioBusqueda1);
        radioPrecioBusqueda1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        radioPrecioBusqueda1.setForeground(new java.awt.Color(0, 0, 0));
        radioPrecioBusqueda1.setText("Precio Menor A:");
        jPanel2.add(radioPrecioBusqueda1);
        radioPrecioBusqueda1.setBounds(270, 150, 200, 25);

        comboPrecioBusqueda1.setBackground(new java.awt.Color(214, 198, 152));
        comboPrecioBusqueda1.setForeground(new java.awt.Color(0, 0, 0));
        jPanel2.add(comboPrecioBusqueda1);
        comboPrecioBusqueda1.setBounds(270, 180, 210, 26);

        groupBusquedaVehiculos.add(radioAnioBusqueda1);
        radioAnioBusqueda1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        radioAnioBusqueda1.setForeground(new java.awt.Color(0, 0, 0));
        radioAnioBusqueda1.setText("Año de Fabricación");
        jPanel2.add(radioAnioBusqueda1);
        radioAnioBusqueda1.setBounds(30, 150, 200, 25);

        comboAnioBusqueda1.setBackground(new java.awt.Color(214, 198, 152));
        comboAnioBusqueda1.setForeground(new java.awt.Color(0, 0, 0));
        jPanel2.add(comboAnioBusqueda1);
        comboAnioBusqueda1.setBounds(30, 180, 210, 26);

        groupBusquedaVehiculos.add(radioEstadoBusqueda1);
        radioEstadoBusqueda1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        radioEstadoBusqueda1.setForeground(new java.awt.Color(0, 0, 0));
        radioEstadoBusqueda1.setText("Estado");
        jPanel2.add(radioEstadoBusqueda1);
        radioEstadoBusqueda1.setBounds(30, 220, 200, 25);

        tablaVehiculos.setBackground(new java.awt.Color(247, 227, 178));
        tablaVehiculos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID_Vehiculo", "Numero_Serie", "ID_Modelo", "Fecha_Fabricacion", "Precio", "Kilometraje", "Fecha_Entrada", "Tipo", "Estado"
            }
        ));
        tablaVehiculos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tablaVehiculosMouseReleased(evt);
            }
        });
        jScrollPane1.setViewportView(tablaVehiculos);

        jPanel2.add(jScrollPane1);
        jScrollPane1.setBounds(20, 290, 720, 270);

        internalVehiculos.getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 0, 760, 580);

        jDesktopPane1.add(internalVehiculos);
        internalVehiculos.setBounds(0, 0, 770, 610);

        internalModelos.setTitle("Modelos");
        internalModelos.setVisible(true);
        internalModelos.getContentPane().setLayout(null);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(null);

        tablaModelos.setBackground(new java.awt.Color(214, 198, 152));
        tablaModelos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tablaModelos);

        jPanel3.add(jScrollPane2);
        jScrollPane2.setBounds(20, 260, 720, 280);

        jPanel11.setBackground(new java.awt.Color(214, 198, 152));
        jPanel11.setLayout(null);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Modelos");
        jPanel11.add(jLabel3);
        jLabel3.setBounds(70, 130, 420, 90);

        btnEliminarModelos.setBackground(new java.awt.Color(227, 211, 163));
        btnEliminarModelos.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnEliminarModelos.setForeground(new java.awt.Color(0, 0, 0));
        btnEliminarModelos.setIcon(new javax.swing.ImageIcon("C:\\Users\\eduar\\Documents\\ITSJ\\5. Quinto Semestre\\Taller de bases de datos\\Proyecto final\\Proyecto_Final_TBD_Escritorio\\src\\main\\java\\img\\eliminar.png")); // NOI18N
        btnEliminarModelos.setText("Eliminar");
        btnEliminarModelos.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        btnEliminarModelos.setEnabled(false);
        jPanel11.add(btnEliminarModelos);
        btnEliminarModelos.setBounds(520, 10, 120, 40);

        btnAgregarModelos.setBackground(new java.awt.Color(227, 211, 163));
        btnAgregarModelos.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnAgregarModelos.setForeground(new java.awt.Color(0, 0, 0));
        btnAgregarModelos.setIcon(new javax.swing.ImageIcon("C:\\Users\\eduar\\Documents\\ITSJ\\5. Quinto Semestre\\Taller de bases de datos\\Proyecto final\\Proyecto_Final_TBD_Escritorio\\src\\main\\java\\img\\agregar.png")); // NOI18N
        btnAgregarModelos.setText("Agregar");
        btnAgregarModelos.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        btnAgregarModelos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarModelosActionPerformed(evt);
            }
        });
        jPanel11.add(btnAgregarModelos);
        btnAgregarModelos.setBounds(230, 10, 120, 40);

        jLabel20.setIcon(new javax.swing.ImageIcon("C:\\Users\\eduar\\Documents\\ITSJ\\5. Quinto Semestre\\Taller de bases de datos\\Proyecto final\\Proyecto_Final_TBD_Escritorio\\src\\main\\java\\img\\logo_oscuro.png")); // NOI18N
        jPanel11.add(jLabel20);
        jLabel20.setBounds(690, 0, 50, 58);

        btnActualizarModelos.setBackground(new java.awt.Color(227, 211, 163));
        btnActualizarModelos.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnActualizarModelos.setForeground(new java.awt.Color(0, 0, 0));
        btnActualizarModelos.setIcon(new javax.swing.ImageIcon("C:\\Users\\eduar\\Documents\\ITSJ\\5. Quinto Semestre\\Taller de bases de datos\\Proyecto final\\Proyecto_Final_TBD_Escritorio\\src\\main\\java\\img\\actualizar.png")); // NOI18N
        btnActualizarModelos.setText("Actualizar");
        btnActualizarModelos.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        btnActualizarModelos.setEnabled(false);
        jPanel11.add(btnActualizarModelos);
        btnActualizarModelos.setBounds(370, 10, 130, 40);

        jLabel23.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(0, 0, 0));
        jLabel23.setText("Modelos");
        jPanel11.add(jLabel23);
        jLabel23.setBounds(10, 0, 140, 50);

        jPanel3.add(jPanel11);
        jPanel11.setBounds(0, 0, 760, 60);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel3.add(jComboBox1);
        jComboBox1.setBounds(270, 70, 150, 30);

        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Buscar por");
        jPanel3.add(jLabel7);
        jLabel7.setBounds(50, 70, 170, 30);

        internalModelos.getContentPane().add(jPanel3);
        jPanel3.setBounds(0, 0, 760, 580);

        jDesktopPane1.add(internalModelos);
        internalModelos.setBounds(0, 0, 770, 610);

        internalVentas.setTitle("Ventas");
        internalVentas.setVisible(false);
        internalVentas.getContentPane().setLayout(null);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(null);

        jPanel16.setBackground(new java.awt.Color(214, 198, 152));
        jPanel16.setLayout(null);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Ventas");
        jPanel16.add(jLabel4);
        jLabel4.setBounds(10, 10, 90, 40);

        btnEliminarVentas.setBackground(new java.awt.Color(227, 211, 163));
        btnEliminarVentas.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnEliminarVentas.setForeground(new java.awt.Color(0, 0, 0));
        btnEliminarVentas.setIcon(new javax.swing.ImageIcon("C:\\Users\\eduar\\Documents\\ITSJ\\5. Quinto Semestre\\Taller de bases de datos\\Proyecto final\\Proyecto_Final_TBD_Escritorio\\src\\main\\java\\img\\eliminar.png")); // NOI18N
        btnEliminarVentas.setText("Eliminar");
        btnEliminarVentas.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        btnEliminarVentas.setEnabled(false);
        jPanel16.add(btnEliminarVentas);
        btnEliminarVentas.setBounds(560, 10, 120, 40);

        btnAgregarVentas.setBackground(new java.awt.Color(227, 211, 163));
        btnAgregarVentas.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnAgregarVentas.setForeground(new java.awt.Color(0, 0, 0));
        btnAgregarVentas.setIcon(new javax.swing.ImageIcon("C:\\Users\\eduar\\Documents\\ITSJ\\5. Quinto Semestre\\Taller de bases de datos\\Proyecto final\\Proyecto_Final_TBD_Escritorio\\src\\main\\java\\img\\agregar.png")); // NOI18N
        btnAgregarVentas.setText("Agregar");
        btnAgregarVentas.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jPanel16.add(btnAgregarVentas);
        btnAgregarVentas.setBounds(290, 10, 120, 40);

        btnActualizarVentas.setBackground(new java.awt.Color(227, 211, 163));
        btnActualizarVentas.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnActualizarVentas.setForeground(new java.awt.Color(0, 0, 0));
        btnActualizarVentas.setIcon(new javax.swing.ImageIcon("C:\\Users\\eduar\\Documents\\ITSJ\\5. Quinto Semestre\\Taller de bases de datos\\Proyecto final\\Proyecto_Final_TBD_Escritorio\\src\\main\\java\\img\\actualizar.png")); // NOI18N
        btnActualizarVentas.setText("Actualizar");
        btnActualizarVentas.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        btnActualizarVentas.setEnabled(false);
        jPanel16.add(btnActualizarVentas);
        btnActualizarVentas.setBounds(420, 10, 130, 40);

        jLabel62.setIcon(new javax.swing.ImageIcon("C:\\Users\\eduar\\Documents\\ITSJ\\5. Quinto Semestre\\Taller de bases de datos\\Proyecto final\\Proyecto_Final_TBD_Escritorio\\src\\main\\java\\img\\logo_oscuro.png")); // NOI18N
        jPanel16.add(jLabel62);
        jLabel62.setBounds(700, 10, 50, 40);

        jPanel4.add(jPanel16);
        jPanel16.setBounds(0, 0, 760, 60);

        groupBusquedaVentas.add(radioIDVentaVentas);
        radioIDVentaVentas.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        radioIDVentaVentas.setForeground(new java.awt.Color(0, 0, 0));
        radioIDVentaVentas.setText("ID Venta");
        jPanel4.add(radioIDVentaVentas);
        radioIDVentaVentas.setBounds(20, 80, 90, 21);

        groupBusquedaVentas.add(radioTodosVentas);
        radioTodosVentas.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        radioTodosVentas.setForeground(new java.awt.Color(0, 0, 0));
        radioTodosVentas.setSelected(true);
        radioTodosVentas.setText("Mostrar Todas las Ventas");
        jPanel4.add(radioTodosVentas);
        radioTodosVentas.setBounds(280, 180, 170, 21);

        cajaIDVentasBuscar.setBackground(new java.awt.Color(255, 255, 255));
        cajaIDVentasBuscar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jPanel4.add(cajaIDVentasBuscar);
        cajaIDVentasBuscar.setBounds(20, 110, 100, 18);

        comboVentasVehiculosBuscar.setBackground(new java.awt.Color(214, 198, 152));
        comboVentasVehiculosBuscar.setForeground(new java.awt.Color(0, 0, 0));
        jPanel4.add(comboVentasVehiculosBuscar);
        comboVentasVehiculosBuscar.setBounds(150, 180, 120, 26);

        groupBusquedaVentas.add(radioMesVentas);
        radioMesVentas.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        radioMesVentas.setForeground(new java.awt.Color(0, 0, 0));
        radioMesVentas.setText("Mes");
        jPanel4.add(radioMesVentas);
        radioMesVentas.setBounds(160, 80, 90, 21);

        comboVentasMesBuscar.setBackground(new java.awt.Color(214, 198, 152));
        comboVentasMesBuscar.setForeground(new java.awt.Color(0, 0, 0));
        jPanel4.add(comboVentasMesBuscar);
        comboVentasMesBuscar.setBounds(160, 110, 76, 26);

        groupBusquedaVentas.add(radioPrecioVentas);
        radioPrecioVentas.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        radioPrecioVentas.setForeground(new java.awt.Color(0, 0, 0));
        radioPrecioVentas.setText("Precio Menor A");
        jPanel4.add(radioPrecioVentas);
        radioPrecioVentas.setBounds(260, 80, 130, 21);

        comboVentasPrecioBuscar.setBackground(new java.awt.Color(214, 198, 152));
        comboVentasPrecioBuscar.setForeground(new java.awt.Color(0, 0, 0));
        jPanel4.add(comboVentasPrecioBuscar);
        comboVentasPrecioBuscar.setBounds(260, 110, 120, 26);

        groupBusquedaVentas.add(radioIdClienteVentas);
        radioIdClienteVentas.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        radioIdClienteVentas.setForeground(new java.awt.Color(0, 0, 0));
        radioIdClienteVentas.setText("ID Cliente");
        jPanel4.add(radioIdClienteVentas);
        radioIdClienteVentas.setBounds(550, 80, 100, 21);

        comboVentasClienteBuscar.setBackground(new java.awt.Color(214, 198, 152));
        comboVentasClienteBuscar.setForeground(new java.awt.Color(0, 0, 0));
        jPanel4.add(comboVentasClienteBuscar);
        comboVentasClienteBuscar.setBounds(550, 110, 120, 26);

        groupBusquedaVentas.add(radioIDEmpleadoVentas);
        radioIDEmpleadoVentas.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        radioIDEmpleadoVentas.setForeground(new java.awt.Color(0, 0, 0));
        radioIDEmpleadoVentas.setText("ID Empleado");
        jPanel4.add(radioIDEmpleadoVentas);
        radioIDEmpleadoVentas.setBounds(10, 150, 100, 21);

        comboVentasEmpleadoBuscar.setBackground(new java.awt.Color(214, 198, 152));
        comboVentasEmpleadoBuscar.setForeground(new java.awt.Color(0, 0, 0));
        jPanel4.add(comboVentasEmpleadoBuscar);
        comboVentasEmpleadoBuscar.setBounds(10, 180, 120, 26);

        groupBusquedaVentas.add(radioIDVehiculoVentas);
        radioIDVehiculoVentas.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        radioIDVehiculoVentas.setForeground(new java.awt.Color(0, 0, 0));
        radioIDVehiculoVentas.setText("ID Vehiculo");
        jPanel4.add(radioIDVehiculoVentas);
        radioIDVehiculoVentas.setBounds(160, 150, 100, 21);

        tablaVentas.setBackground(new java.awt.Color(214, 198, 152));
        tablaVentas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(tablaVentas);

        jPanel4.add(jScrollPane3);
        jScrollPane3.setBounds(20, 310, 720, 240);

        groupBusquedaVentas.add(radioVentasPagoBuscar);
        radioVentasPagoBuscar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        radioVentasPagoBuscar.setForeground(new java.awt.Color(0, 0, 0));
        radioVentasPagoBuscar.setText("Forma de Pago");
        jPanel4.add(radioVentasPagoBuscar);
        radioVentasPagoBuscar.setBounds(410, 80, 110, 21);

        comboVentasPagoBuscar.setBackground(new java.awt.Color(214, 198, 152));
        comboVentasPagoBuscar.setForeground(new java.awt.Color(0, 0, 0));
        jPanel4.add(comboVentasPagoBuscar);
        comboVentasPagoBuscar.setBounds(410, 110, 120, 26);

        internalVentas.getContentPane().add(jPanel4);
        jPanel4.setBounds(0, 0, 760, 580);

        jDesktopPane1.add(internalVentas);
        internalVentas.setBounds(0, 0, 770, 620);

        internalProximamente.setTitle("Proximamente");
        internalProximamente.setVisible(false);
        internalProximamente.getContentPane().setLayout(null);

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setLayout(null);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Estamos trabajando en la construcción de esta página");
        jPanel5.add(jLabel5);
        jLabel5.setBounds(60, 50, 640, 80);

        internalProximamente.getContentPane().add(jPanel5);
        jPanel5.setBounds(0, 0, 760, 580);

        jDesktopPane1.add(internalProximamente);
        internalProximamente.setBounds(0, 0, 770, 610);

        internalVehiculosEliminados.setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        internalVehiculosEliminados.setTitle("Historial de Vehiculos");
        internalVehiculosEliminados.setVisible(false);

        jPanel22.setBackground(new java.awt.Color(255, 255, 255));
        jPanel22.setLayout(null);

        jPanel23.setBackground(new java.awt.Color(214, 198, 152));
        jPanel23.setLayout(null);

        jLabel83.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel83.setForeground(new java.awt.Color(0, 0, 0));
        jLabel83.setText("Vehiculos Eliminados");
        jPanel23.add(jLabel83);
        jLabel83.setBounds(10, 10, 140, 30);

        jLabel84.setIcon(new javax.swing.ImageIcon("C:\\Users\\eduar\\Documents\\ITSJ\\5. Quinto Semestre\\Taller de bases de datos\\Proyecto final\\Proyecto_Final_TBD_Escritorio\\src\\main\\java\\img\\logo_oscuro.png")); // NOI18N
        jPanel23.add(jLabel84);
        jLabel84.setBounds(360, 0, 50, 50);

        jPanel22.add(jPanel23);
        jPanel23.setBounds(0, 0, 410, 50);

        tablaVehiculosEliminados.setBackground(new java.awt.Color(247, 227, 178));
        tablaVehiculosEliminados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane4.setViewportView(tablaVehiculosEliminados);

        jPanel22.add(jScrollPane4);
        jScrollPane4.setBounds(10, 60, 390, 220);

        btnVehiculosEliminadosCerrar.setBackground(new java.awt.Color(227, 211, 163));
        btnVehiculosEliminadosCerrar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnVehiculosEliminadosCerrar.setForeground(new java.awt.Color(0, 0, 0));
        btnVehiculosEliminadosCerrar.setText("Cerrar Ventana");
        btnVehiculosEliminadosCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVehiculosEliminadosCerrarActionPerformed(evt);
            }
        });
        jPanel22.add(btnVehiculosEliminadosCerrar);
        btnVehiculosEliminadosCerrar.setBounds(130, 310, 140, 50);

        javax.swing.GroupLayout internalVehiculosEliminadosLayout = new javax.swing.GroupLayout(internalVehiculosEliminados.getContentPane());
        internalVehiculosEliminados.getContentPane().setLayout(internalVehiculosEliminadosLayout);
        internalVehiculosEliminadosLayout.setHorizontalGroup(
            internalVehiculosEliminadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel22, javax.swing.GroupLayout.DEFAULT_SIZE, 408, Short.MAX_VALUE)
        );
        internalVehiculosEliminadosLayout.setVerticalGroup(
            internalVehiculosEliminadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel22, javax.swing.GroupLayout.DEFAULT_SIZE, 404, Short.MAX_VALUE)
        );

        jDesktopPane1.add(internalVehiculosEliminados);
        internalVehiculosEliminados.setBounds(120, 40, 420, 440);

        internalAgregarModelos.setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        internalAgregarModelos.setTitle("Agregar Modelos");
        internalAgregarModelos.setVisible(false);
        internalAgregarModelos.getContentPane().setLayout(null);

        jPanel12.setBackground(new java.awt.Color(255, 255, 255));
        jPanel12.setLayout(null);

        jPanel13.setBackground(new java.awt.Color(214, 198, 152));
        jPanel13.setLayout(null);

        jLabel38.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel38.setForeground(new java.awt.Color(0, 0, 0));
        jLabel38.setText("Agregar Modelos");
        jPanel13.add(jLabel38);
        jLabel38.setBounds(20, 20, 140, 20);
        jPanel13.add(jLabel39);
        jLabel39.setBounds(330, 20, 0, 0);

        jLabel40.setIcon(new javax.swing.ImageIcon("C:\\Users\\eduar\\Documents\\ITSJ\\5. Quinto Semestre\\Taller de bases de datos\\Proyecto final\\Proyecto_Final_TBD_Escritorio\\src\\main\\java\\img\\logo_oscuro.png")); // NOI18N
        jPanel13.add(jLabel40);
        jLabel40.setBounds(370, 0, 60, 60);

        jPanel12.add(jPanel13);
        jPanel13.setBounds(0, 0, 430, 60);

        jLabel41.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel41.setForeground(new java.awt.Color(0, 0, 0));
        jLabel41.setText("País Fabricación");
        jPanel12.add(jLabel41);
        jLabel41.setBounds(10, 320, 150, 16);

        jLabel42.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel42.setForeground(new java.awt.Color(0, 0, 0));
        jLabel42.setText("Nombre Modelo:");
        jPanel12.add(jLabel42);
        jLabel42.setBounds(10, 80, 150, 16);

        jLabel43.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel43.setForeground(new java.awt.Color(0, 0, 0));
        jLabel43.setText("Año Modelo");
        jPanel12.add(jLabel43);
        jLabel43.setBounds(10, 110, 150, 16);

        jLabel44.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel44.setForeground(new java.awt.Color(0, 0, 0));
        jLabel44.setText("Fabricante");
        jPanel12.add(jLabel44);
        jLabel44.setBounds(10, 140, 150, 16);

        jLabel45.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel45.setForeground(new java.awt.Color(0, 0, 0));
        jLabel45.setText("Número Cilindros");
        jPanel12.add(jLabel45);
        jLabel45.setBounds(10, 170, 150, 16);

        jLabel46.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel46.setForeground(new java.awt.Color(0, 0, 0));
        jLabel46.setText("Número Puertas");
        jPanel12.add(jLabel46);
        jLabel46.setBounds(10, 200, 150, 16);

        jLabel47.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel47.setForeground(new java.awt.Color(0, 0, 0));
        jLabel47.setText("Peso (KG)");
        jPanel12.add(jLabel47);
        jLabel47.setBounds(10, 230, 150, 16);

        jLabel48.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel48.setForeground(new java.awt.Color(0, 0, 0));
        jLabel48.setText("Capacidad Pasajeros");
        jPanel12.add(jLabel48);
        jLabel48.setBounds(10, 260, 150, 16);

        jLabel49.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel49.setForeground(new java.awt.Color(0, 0, 0));
        jLabel49.setText("Color Base");
        jPanel12.add(jLabel49);
        jLabel49.setBounds(10, 290, 150, 16);

        cajaModelosPaisAgregar.setBackground(new java.awt.Color(255, 255, 255));
        cajaModelosPaisAgregar.setForeground(new java.awt.Color(0, 0, 0));
        cajaModelosPaisAgregar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jPanel12.add(cajaModelosPaisAgregar);
        cajaModelosPaisAgregar.setBounds(160, 320, 250, 20);

        cajaModelosNombreAgregar.setBackground(new java.awt.Color(255, 255, 255));
        cajaModelosNombreAgregar.setForeground(new java.awt.Color(0, 0, 0));
        cajaModelosNombreAgregar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jPanel12.add(cajaModelosNombreAgregar);
        cajaModelosNombreAgregar.setBounds(160, 80, 250, 20);

        cajaModelosFabricanteAgregar.setBackground(new java.awt.Color(255, 255, 255));
        cajaModelosFabricanteAgregar.setForeground(new java.awt.Color(0, 0, 0));
        cajaModelosFabricanteAgregar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jPanel12.add(cajaModelosFabricanteAgregar);
        cajaModelosFabricanteAgregar.setBounds(160, 140, 250, 20);

        cajaModelosColorAgregar.setBackground(new java.awt.Color(255, 255, 255));
        cajaModelosColorAgregar.setForeground(new java.awt.Color(0, 0, 0));
        cajaModelosColorAgregar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jPanel12.add(cajaModelosColorAgregar);
        cajaModelosColorAgregar.setBounds(160, 290, 250, 20);

        comboModelosCilindrosAgregar.setBackground(new java.awt.Color(214, 198, 152));
        comboModelosCilindrosAgregar.setForeground(new java.awt.Color(0, 0, 0));
        jPanel12.add(comboModelosCilindrosAgregar);
        comboModelosCilindrosAgregar.setBounds(160, 170, 250, 26);

        comboModelosAnioAgregar.setBackground(new java.awt.Color(214, 198, 152));
        comboModelosAnioAgregar.setForeground(new java.awt.Color(0, 0, 0));
        jPanel12.add(comboModelosAnioAgregar);
        comboModelosAnioAgregar.setBounds(160, 110, 250, 26);

        btnModelosCancelarAgregar.setBackground(new java.awt.Color(227, 211, 163));
        btnModelosCancelarAgregar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnModelosCancelarAgregar.setForeground(new java.awt.Color(0, 0, 0));
        btnModelosCancelarAgregar.setIcon(new javax.swing.ImageIcon("C:\\Users\\eduar\\Documents\\ITSJ\\5. Quinto Semestre\\Taller de bases de datos\\Proyecto final\\Proyecto_Final_TBD_Escritorio\\src\\main\\java\\img\\cancelar.png")); // NOI18N
        btnModelosCancelarAgregar.setText("Cancelar");
        jPanel12.add(btnModelosCancelarAgregar);
        btnModelosCancelarAgregar.setBounds(290, 400, 120, 40);

        btnModelosAgregarAgregar.setBackground(new java.awt.Color(227, 211, 163));
        btnModelosAgregarAgregar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnModelosAgregarAgregar.setForeground(new java.awt.Color(0, 0, 0));
        btnModelosAgregarAgregar.setIcon(new javax.swing.ImageIcon("C:\\Users\\eduar\\Documents\\ITSJ\\5. Quinto Semestre\\Taller de bases de datos\\Proyecto final\\Proyecto_Final_TBD_Escritorio\\src\\main\\java\\img\\agregar.png")); // NOI18N
        btnModelosAgregarAgregar.setText("Agregar");
        btnModelosAgregarAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModelosAgregarAgregarActionPerformed(evt);
            }
        });
        jPanel12.add(btnModelosAgregarAgregar);
        btnModelosAgregarAgregar.setBounds(10, 400, 120, 40);

        btnModelosRestaurarAgregar.setBackground(new java.awt.Color(227, 211, 163));
        btnModelosRestaurarAgregar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnModelosRestaurarAgregar.setForeground(new java.awt.Color(0, 0, 0));
        btnModelosRestaurarAgregar.setIcon(new javax.swing.ImageIcon("C:\\Users\\eduar\\Documents\\ITSJ\\5. Quinto Semestre\\Taller de bases de datos\\Proyecto final\\Proyecto_Final_TBD_Escritorio\\src\\main\\java\\img\\restaurar.png")); // NOI18N
        btnModelosRestaurarAgregar.setText("Restaurar");
        jPanel12.add(btnModelosRestaurarAgregar);
        btnModelosRestaurarAgregar.setBounds(150, 400, 120, 40);

        cajaModelosPasajerosAgregar.setBackground(new java.awt.Color(255, 255, 255));
        cajaModelosPasajerosAgregar.setForeground(new java.awt.Color(0, 0, 0));
        cajaModelosPasajerosAgregar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jPanel12.add(cajaModelosPasajerosAgregar);
        cajaModelosPasajerosAgregar.setBounds(160, 260, 250, 20);

        cajaModelosPuertasAgregar.setBackground(new java.awt.Color(255, 255, 255));
        cajaModelosPuertasAgregar.setForeground(new java.awt.Color(0, 0, 0));
        cajaModelosPuertasAgregar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jPanel12.add(cajaModelosPuertasAgregar);
        cajaModelosPuertasAgregar.setBounds(160, 200, 250, 20);

        cajaModelosPesoAgregar.setBackground(new java.awt.Color(255, 255, 255));
        cajaModelosPesoAgregar.setForeground(new java.awt.Color(0, 0, 0));
        cajaModelosPesoAgregar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jPanel12.add(cajaModelosPesoAgregar);
        cajaModelosPesoAgregar.setBounds(160, 230, 250, 20);

        internalAgregarModelos.getContentPane().add(jPanel12);
        jPanel12.setBounds(0, 0, 430, 510);

        jDesktopPane1.add(internalAgregarModelos);
        internalAgregarModelos.setBounds(150, 30, 440, 540);

        internalCambiosModelos.setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        internalCambiosModelos.setTitle("Actualizar Modelos");
        internalCambiosModelos.setVisible(false);
        internalCambiosModelos.getContentPane().setLayout(null);

        jPanel14.setBackground(new java.awt.Color(255, 255, 255));
        jPanel14.setLayout(null);

        jPanel15.setBackground(new java.awt.Color(214, 198, 152));
        jPanel15.setLayout(null);

        jLabel50.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel50.setForeground(new java.awt.Color(0, 0, 0));
        jLabel50.setText("Actualizar Modelos");
        jPanel15.add(jLabel50);
        jLabel50.setBounds(20, 20, 140, 20);
        jPanel15.add(jLabel51);
        jLabel51.setBounds(330, 20, 0, 0);

        jLabel52.setIcon(new javax.swing.ImageIcon("C:\\Users\\eduar\\Documents\\ITSJ\\5. Quinto Semestre\\Taller de bases de datos\\Proyecto final\\Proyecto_Final_TBD_Escritorio\\src\\main\\java\\img\\logo_oscuro.png")); // NOI18N
        jPanel15.add(jLabel52);
        jLabel52.setBounds(370, 0, 60, 60);

        jPanel14.add(jPanel15);
        jPanel15.setBounds(0, 0, 430, 60);

        jLabel53.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel53.setForeground(new java.awt.Color(0, 0, 0));
        jLabel53.setText("País Fabricación");
        jPanel14.add(jLabel53);
        jLabel53.setBounds(10, 320, 150, 16);

        jLabel54.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel54.setForeground(new java.awt.Color(0, 0, 0));
        jLabel54.setText("Nombre Modelo:");
        jPanel14.add(jLabel54);
        jLabel54.setBounds(10, 80, 150, 16);

        jLabel55.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel55.setForeground(new java.awt.Color(0, 0, 0));
        jLabel55.setText("Año Modelo");
        jPanel14.add(jLabel55);
        jLabel55.setBounds(10, 110, 150, 16);

        jLabel56.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel56.setForeground(new java.awt.Color(0, 0, 0));
        jLabel56.setText("Fabricante");
        jPanel14.add(jLabel56);
        jLabel56.setBounds(10, 140, 150, 16);

        jLabel57.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel57.setForeground(new java.awt.Color(0, 0, 0));
        jLabel57.setText("Número Cilindros");
        jPanel14.add(jLabel57);
        jLabel57.setBounds(10, 170, 150, 16);

        jLabel58.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel58.setForeground(new java.awt.Color(0, 0, 0));
        jLabel58.setText("Número Puertas");
        jPanel14.add(jLabel58);
        jLabel58.setBounds(10, 200, 150, 16);

        jLabel59.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel59.setForeground(new java.awt.Color(0, 0, 0));
        jLabel59.setText("Peso (KG)");
        jPanel14.add(jLabel59);
        jLabel59.setBounds(10, 230, 150, 16);

        jLabel60.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel60.setForeground(new java.awt.Color(0, 0, 0));
        jLabel60.setText("Capacidad Pasajeros");
        jPanel14.add(jLabel60);
        jLabel60.setBounds(10, 260, 150, 16);

        jLabel61.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel61.setForeground(new java.awt.Color(0, 0, 0));
        jLabel61.setText("Color Base");
        jPanel14.add(jLabel61);
        jLabel61.setBounds(10, 290, 150, 16);

        cajaModelosPaisActualizar.setBackground(new java.awt.Color(255, 255, 255));
        cajaModelosPaisActualizar.setForeground(new java.awt.Color(0, 0, 0));
        cajaModelosPaisActualizar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jPanel14.add(cajaModelosPaisActualizar);
        cajaModelosPaisActualizar.setBounds(160, 320, 250, 20);

        cajaModelosNombreActualizar.setBackground(new java.awt.Color(255, 255, 255));
        cajaModelosNombreActualizar.setForeground(new java.awt.Color(0, 0, 0));
        cajaModelosNombreActualizar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jPanel14.add(cajaModelosNombreActualizar);
        cajaModelosNombreActualizar.setBounds(160, 80, 250, 20);

        cajaModelosFabricanteActualizar.setBackground(new java.awt.Color(255, 255, 255));
        cajaModelosFabricanteActualizar.setForeground(new java.awt.Color(0, 0, 0));
        cajaModelosFabricanteActualizar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jPanel14.add(cajaModelosFabricanteActualizar);
        cajaModelosFabricanteActualizar.setBounds(160, 140, 250, 20);

        cajaModelosColorActualizar.setBackground(new java.awt.Color(255, 255, 255));
        cajaModelosColorActualizar.setForeground(new java.awt.Color(0, 0, 0));
        cajaModelosColorActualizar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jPanel14.add(cajaModelosColorActualizar);
        cajaModelosColorActualizar.setBounds(160, 290, 250, 20);

        comboModelosCilindrosActualizar.setBackground(new java.awt.Color(214, 198, 152));
        comboModelosCilindrosActualizar.setForeground(new java.awt.Color(0, 0, 0));
        jPanel14.add(comboModelosCilindrosActualizar);
        comboModelosCilindrosActualizar.setBounds(160, 170, 250, 26);

        comboModelosAnioActualizar.setBackground(new java.awt.Color(214, 198, 152));
        comboModelosAnioActualizar.setForeground(new java.awt.Color(0, 0, 0));
        jPanel14.add(comboModelosAnioActualizar);
        comboModelosAnioActualizar.setBounds(160, 110, 250, 26);

        btnModelosCancelarActualizar.setBackground(new java.awt.Color(227, 211, 163));
        btnModelosCancelarActualizar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnModelosCancelarActualizar.setForeground(new java.awt.Color(0, 0, 0));
        btnModelosCancelarActualizar.setIcon(new javax.swing.ImageIcon("C:\\Users\\eduar\\Documents\\ITSJ\\5. Quinto Semestre\\Taller de bases de datos\\Proyecto final\\Proyecto_Final_TBD_Escritorio\\src\\main\\java\\img\\cancelar.png")); // NOI18N
        btnModelosCancelarActualizar.setText("Cancelar");
        jPanel14.add(btnModelosCancelarActualizar);
        btnModelosCancelarActualizar.setBounds(260, 400, 120, 40);

        btnModelosActualizarActualizar.setBackground(new java.awt.Color(227, 211, 163));
        btnModelosActualizarActualizar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnModelosActualizarActualizar.setForeground(new java.awt.Color(0, 0, 0));
        btnModelosActualizarActualizar.setIcon(new javax.swing.ImageIcon("C:\\Users\\eduar\\Documents\\ITSJ\\5. Quinto Semestre\\Taller de bases de datos\\Proyecto final\\Proyecto_Final_TBD_Escritorio\\src\\main\\java\\img\\actualizar.png")); // NOI18N
        btnModelosActualizarActualizar.setText("Actualizar");
        jPanel14.add(btnModelosActualizarActualizar);
        btnModelosActualizarActualizar.setBounds(50, 400, 120, 40);

        cajaModelosPasajerosActualizar.setBackground(new java.awt.Color(255, 255, 255));
        cajaModelosPasajerosActualizar.setForeground(new java.awt.Color(0, 0, 0));
        cajaModelosPasajerosActualizar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jPanel14.add(cajaModelosPasajerosActualizar);
        cajaModelosPasajerosActualizar.setBounds(160, 260, 250, 20);

        cajaModelosPuertasActualizar.setBackground(new java.awt.Color(255, 255, 255));
        cajaModelosPuertasActualizar.setForeground(new java.awt.Color(0, 0, 0));
        cajaModelosPuertasActualizar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jPanel14.add(cajaModelosPuertasActualizar);
        cajaModelosPuertasActualizar.setBounds(160, 200, 250, 20);

        cajaModelosPesoActualizar.setBackground(new java.awt.Color(255, 255, 255));
        cajaModelosPesoActualizar.setForeground(new java.awt.Color(0, 0, 0));
        cajaModelosPesoActualizar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jPanel14.add(cajaModelosPesoActualizar);
        cajaModelosPesoActualizar.setBounds(160, 230, 250, 20);

        internalCambiosModelos.getContentPane().add(jPanel14);
        jPanel14.setBounds(0, 0, 430, 510);

        jDesktopPane1.add(internalCambiosModelos);
        internalCambiosModelos.setBounds(150, 30, 440, 540);

        bg.add(jDesktopPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 0, 770, 610));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(bg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cargarCombosModelos() {
        comboModelosAnioAgregar.removeAllItems();
        comboModelosCilindrosAgregar.removeAllItems();

        for (Integer anio : ComboBoxUtil.getAnios()) {
            comboModelosAnioAgregar.addItem(String.valueOf(anio));
        }

        for (Integer cilindros : ComboBoxUtil.getCilindros()) {
            comboModelosCilindrosAgregar.addItem(String.valueOf(cilindros));
        }
    }
    
    private void abrirEditarModelo(int idModelo) {
        Modelo modelo = modeloService.obtenerPorId(idModelo);
        if (modelo != null) {

            cajaModelosNombreActualizar.setText(modelo.getNombreModelo());
            cajaModelosFabricanteActualizar.setText(modelo.getFabricante());
            cajaModelosPuertasActualizar.setText(String.valueOf(modelo.getNumeroPuertas()));
            cajaModelosPesoActualizar.setText(String.valueOf(modelo.getPesoKg()));
            cajaModelosPasajerosActualizar.setText(String.valueOf(modelo.getCapacidadPasajeros()));
            cajaModelosColorActualizar.setText(modelo.getColorBase());
            cajaModelosPaisActualizar.setText(modelo.getPaisFabricacion());
            comboModelosAnioActualizar.setSelectedItem(String.valueOf(modelo.getAnioModelo()));
            comboModelosCilindrosActualizar.setSelectedItem(String.valueOf(modelo.getNumeroCilindros()));

            internalCambiosModelos.setVisible(true);
            internalCambiosModelos.toFront();
        }
    }

    private void confirmarEliminar(int idModelo) {
        int respuesta = JOptionPane.showConfirmDialog(
            this,
            "¿Estás seguro de eliminar el modelo con ID " + idModelo + "?",
            "Confirmar eliminación",
            JOptionPane.YES_NO_OPTION,
            JOptionPane.WARNING_MESSAGE
        );

        if (respuesta == JOptionPane.YES_OPTION) {
            modeloService.eliminar(idModelo);
            JOptionPane.showMessageDialog(this, "Modelo eliminado correctamente");
            cargarTablaModelos();
        }
    }

    
    private void cargarTablaModelos() {
        String[] columnas = {"ID", "Nombre", "Año", "Fabricante", "Cilindros",
                             "Puertas", "Peso (kg)", "Pasajeros", "Color", "País",
                             "Editar", "Eliminar"};

        DefaultTableModel tableModel = new DefaultTableModel(columnas, 0){
            
            @Override
            public boolean isCellEditable(int row, int column) {
                // Solo las columnas de botones son editables
                return column == 10 || column == 11;
            }
            
        };

        for (Modelo m : modeloService.obtenerTodos()) {
            tableModel.addRow(new Object[]{
                m.getIdModelo(),
                m.getNombreModelo(),
                m.getAnioModelo(),
                m.getFabricante(),
                m.getNumeroCilindros(),
                m.getNumeroPuertas(),
                m.getPesoKg(),
                m.getCapacidadPasajeros(),
                m.getColorBase(),
                m.getPaisFabricacion(),
                "Editar",
                "Eliminar"    
            });
        }

        tablaModelos.setModel(tableModel);
        
        tablaModelos.getColumnModel().getColumn(10).setCellRenderer(new ButtonRenderer("Editar"));
        tablaModelos.getColumnModel().getColumn(10).setCellEditor(new ButtonEditor("Editar", e -> {
            int fila = tablaModelos.getSelectedRow();
            int idModelo = (int) tablaModelos.getValueAt(fila, 0);
            abrirEditarModelo(idModelo);
        }));

        tablaModelos.getColumnModel().getColumn(11).setCellRenderer(new ButtonRenderer("Eliminar"));
        tablaModelos.getColumnModel().getColumn(11).setCellEditor(new ButtonEditor("Eliminar", e -> {
            int fila = tablaModelos.getSelectedRow();
            int idModelo = (int) tablaModelos.getValueAt(fila, 0);
            confirmarEliminar(idModelo);
        }));
        
    }

    
    // ============================================== VENTANA VEHICULOS ================================================================
    
    private void btnCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarSesionActionPerformed


        
        
        SwingUtilities.invokeLater(new Runnable() {

            @Override
            public void run() {

                new VentanaLogin();

            }
        });
        
        setVisible(false);
        
    }//GEN-LAST:event_btnCerrarSesionActionPerformed

    private void btnHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHomeActionPerformed
        
        nav.marcarBotonActivo(btnHome, btnVehiculos, btnModelos, btnVentas, btnClientes, btnEmpleados, btnDocumentacion);
        
        nav.mostrarPanel(internalHome, internalVehiculos, internalModelos, internalVentas, internalProximamente, internalVehiculosEliminados);
        

       
    }//GEN-LAST:event_btnHomeActionPerformed

    private void btnVehiculosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVehiculosActionPerformed

        nav.marcarBotonActivo(btnVehiculos, btnHome, btnModelos, btnVentas, btnClientes, btnEmpleados, btnDocumentacion);
        
         nav.mostrarPanel(internalVehiculos, internalHome, internalModelos, internalVentas, internalProximamente, internalVehiculosEliminados);
        
    }//GEN-LAST:event_btnVehiculosActionPerformed

    private void btnModelosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModelosActionPerformed

        nav.marcarBotonActivo(btnModelos, btnVehiculos, btnHome, btnVentas, btnClientes, btnEmpleados, btnDocumentacion);
        
        nav.mostrarPanel(internalModelos, internalVehiculos, internalHome, internalVentas, internalProximamente, internalVehiculosEliminados);
        
        cargarTablaModelos();
        
    }//GEN-LAST:event_btnModelosActionPerformed

    private void btnVentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVentasActionPerformed

        nav.marcarBotonActivo(btnVentas, btnVehiculos, btnHome, btnModelos, btnClientes, btnEmpleados, btnDocumentacion);
        
         nav.mostrarPanel(internalVentas, internalVehiculos, internalModelos, internalHome, internalProximamente, internalVehiculosEliminados);
        
    }//GEN-LAST:event_btnVentasActionPerformed

    private void btnEmpleadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEmpleadosActionPerformed

        nav.marcarBotonActivo(btnEmpleados, btnVehiculos, btnHome, btnModelos, btnVentas, btnClientes, btnDocumentacion);
        
         nav.mostrarPanel(internalProximamente, internalVehiculos, internalModelos, internalVentas, internalHome, internalVehiculosEliminados);
        
    }//GEN-LAST:event_btnEmpleadosActionPerformed

    private void btnClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClientesActionPerformed
        

        nav.marcarBotonActivo(btnClientes, btnVehiculos, btnHome, btnModelos, btnVentas, btnEmpleados, btnDocumentacion);
        
        nav.mostrarPanel(internalProximamente, internalVehiculos, internalModelos, internalVentas, internalHome, internalVehiculosEliminados);
        
    }//GEN-LAST:event_btnClientesActionPerformed

    private void btnDocumentacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDocumentacionActionPerformed
        
 
        nav.marcarBotonActivo(btnDocumentacion, btnVehiculos, btnHome, btnModelos, btnVentas, btnEmpleados, btnClientes);
        
        nav.mostrarPanel(internalProximamente, internalVehiculos, internalModelos, internalVentas, internalHome, internalVehiculosEliminados);
        
    }//GEN-LAST:event_btnDocumentacionActionPerformed

    
    
    
    
    
    
    private void btnVehiculosEliminadosCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVehiculosEliminadosCerrarActionPerformed
        
        internalVehiculosEliminados.setVisible(false);
        
    }//GEN-LAST:event_btnVehiculosEliminadosCerrarActionPerformed

    // =============================== Acciones Tabla modelos =======================
    
    private void tablaVehiculosMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaVehiculosMouseReleased

        String nc = (String) tablaVehiculos.getValueAt(tablaVehiculos.getSelectedRow(), 0);
        
        cajaNumVehiculoBuscar.setText(nc);
        
        
        
        // TODO add your handling code here:
    }//GEN-LAST:event_tablaVehiculosMouseReleased

    private void btnAgregarModelosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarModelosActionPerformed
        
        nav.mostrarPanel(internalAgregarModelos);
        
        cargarCombosModelos();
        
    }//GEN-LAST:event_btnAgregarModelosActionPerformed

    private void btnModelosAgregarAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModelosAgregarAgregarActionPerformed
        
        try {
        Modelo modelo = new Modelo(

            cajaModelosNombreAgregar.getText().trim(),
            Integer.parseInt((String) comboModelosAnioAgregar.getSelectedItem()),
            cajaModelosFabricanteAgregar.getText().trim(),
            Integer.parseInt((String) comboModelosCilindrosAgregar.getSelectedItem()),
            Integer.parseInt(cajaModelosPuertasAgregar.getText().trim()),
            Double.parseDouble(cajaModelosPesoAgregar.getText().trim()),
            Integer.parseInt(cajaModelosPasajerosAgregar.getText().trim()),
            cajaModelosColorAgregar.getText().trim(),
            cajaModelosPaisAgregar.getText().trim()
        );

        modeloService.agregar(modelo);
        JOptionPane.showMessageDialog(this, "Modelo agregado correctamente");
        internalAgregarModelos.setVisible(false);
        cargarTablaModelos(); // refresca la tabla

    } catch (IllegalArgumentException e) {
        JOptionPane.showMessageDialog(this, e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
    }
        
    }//GEN-LAST:event_btnModelosAgregarAgregarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new VentanaInicio().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bg;
    private javax.swing.JButton btnActualizarModelos;
    private javax.swing.JButton btnActualizarVentas;
    private javax.swing.JButton btnAgregarModelos;
    private javax.swing.JButton btnAgregarVehiculos;
    private javax.swing.JButton btnAgregarVentas;
    private javax.swing.JButton btnCerrarSesion;
    private javax.swing.JButton btnClientes;
    private javax.swing.JButton btnDocumentacion;
    private javax.swing.JButton btnEliminarModelos;
    private javax.swing.JButton btnEliminarVehiculos;
    private javax.swing.JButton btnEliminarVentas;
    private javax.swing.JButton btnEmpleados;
    private javax.swing.JButton btnHome;
    private javax.swing.JButton btnHomeGrafica;
    private javax.swing.JButton btnHomeHistorialPrecios;
    private javax.swing.JButton btnHomeReporte;
    private javax.swing.JButton btnHomeVehiculosEliminados;
    private javax.swing.JButton btnHomeVista;
    private javax.swing.JButton btnModelos;
    private javax.swing.JButton btnModelosActualizarActualizar;
    private javax.swing.JButton btnModelosAgregarAgregar;
    private javax.swing.JButton btnModelosCancelarActualizar;
    private javax.swing.JButton btnModelosCancelarAgregar;
    private javax.swing.JButton btnModelosRestaurarAgregar;
    private javax.swing.JButton btnModificarVehiculos;
    private javax.swing.JButton btnVehiculos;
    private javax.swing.JButton btnVehiculosEliminadosCerrar;
    private javax.swing.JButton btnVentas;
    private javax.swing.JTextField cajaIDVentasBuscar;
    private javax.swing.JTextField cajaModelosColorActualizar;
    private javax.swing.JTextField cajaModelosColorAgregar;
    private javax.swing.JTextField cajaModelosFabricanteActualizar;
    private javax.swing.JTextField cajaModelosFabricanteAgregar;
    private javax.swing.JTextField cajaModelosNombreActualizar;
    private javax.swing.JTextField cajaModelosNombreAgregar;
    private javax.swing.JTextField cajaModelosPaisActualizar;
    private javax.swing.JTextField cajaModelosPaisAgregar;
    private javax.swing.JTextField cajaModelosPasajerosActualizar;
    private javax.swing.JTextField cajaModelosPasajerosAgregar;
    private javax.swing.JTextField cajaModelosPesoActualizar;
    private javax.swing.JTextField cajaModelosPesoAgregar;
    private javax.swing.JTextField cajaModelosPuertasActualizar;
    private javax.swing.JTextField cajaModelosPuertasAgregar;
    private javax.swing.JTextField cajaNumSerieBuscar;
    private javax.swing.JTextField cajaNumVehiculoBuscar;
    private javax.swing.JComboBox<String> comboAnioBusqueda1;
    private javax.swing.JComboBox<String> comboEstadoBusqueda;
    private javax.swing.JComboBox<String> comboModeloBusqueda;
    private javax.swing.JComboBox<String> comboModelosAnioActualizar;
    private javax.swing.JComboBox<String> comboModelosAnioAgregar;
    private javax.swing.JComboBox<String> comboModelosCilindrosActualizar;
    private javax.swing.JComboBox<String> comboModelosCilindrosAgregar;
    private javax.swing.JComboBox<String> comboPrecioBusqueda1;
    private javax.swing.JComboBox<String> comboTipoBusqueda;
    private javax.swing.JComboBox<String> comboVentasClienteBuscar;
    private javax.swing.JComboBox<String> comboVentasEmpleadoBuscar;
    private javax.swing.JComboBox<String> comboVentasMesBuscar;
    private javax.swing.JComboBox<String> comboVentasPagoBuscar;
    private javax.swing.JComboBox<String> comboVentasPrecioBuscar;
    private javax.swing.JComboBox<String> comboVentasVehiculosBuscar;
    private javax.swing.ButtonGroup groupBusquedaModelos;
    private javax.swing.ButtonGroup groupBusquedaVehiculos;
    private javax.swing.ButtonGroup groupBusquedaVentas;
    private javax.swing.JInternalFrame internalAgregarModelos;
    private javax.swing.JInternalFrame internalCambiosModelos;
    private javax.swing.JInternalFrame internalHome;
    private javax.swing.JInternalFrame internalModelos;
    private javax.swing.JInternalFrame internalProximamente;
    private javax.swing.JInternalFrame internalVehiculos;
    private javax.swing.JInternalFrame internalVehiculosEliminados;
    private javax.swing.JInternalFrame internalVentas;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel60;
    private javax.swing.JLabel jLabel61;
    private javax.swing.JLabel jLabel62;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel81;
    private javax.swing.JLabel jLabel82;
    private javax.swing.JLabel jLabel83;
    private javax.swing.JLabel jLabel84;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel21;
    private javax.swing.JPanel jPanel22;
    private javax.swing.JPanel jPanel23;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JRadioButton radioAnioBusqueda1;
    private javax.swing.JRadioButton radioEstadoBusqueda1;
    private javax.swing.JRadioButton radioIDEmpleadoVentas;
    private javax.swing.JRadioButton radioIDVehiculoVentas;
    private javax.swing.JRadioButton radioIDVentaVentas;
    private javax.swing.JRadioButton radioIdClienteVentas;
    private javax.swing.JRadioButton radioMesVentas;
    private javax.swing.JRadioButton radioModeloBusqueda;
    private javax.swing.JRadioButton radioNumSerieBusqueda;
    private javax.swing.JRadioButton radioNumVehiculoBusqueda;
    private javax.swing.JRadioButton radioPrecioBusqueda1;
    private javax.swing.JRadioButton radioPrecioVentas;
    private javax.swing.JRadioButton radioTipoBusqueda;
    private javax.swing.JRadioButton radioTodosBusqueda;
    private javax.swing.JRadioButton radioTodosVentas;
    private javax.swing.JRadioButton radioVentasPagoBuscar;
    private javax.swing.JPanel sidePane;
    private javax.swing.JTable tablaModelos;
    private javax.swing.JTable tablaVehiculos;
    private javax.swing.JTable tablaVehiculosEliminados;
    private javax.swing.JTable tablaVentas;
    // End of variables declaration//GEN-END:variables
}
